### ISSUE TITLE
Bio::DB::Taxonomy::flatfile needs rewrite

### ISSUE THREAD

**Issue by hyphaltip** [bioperl/bioperl-live#100]
We need to rethink the index structure here now that the number of taxonomy items is so large, DB_File hash interface is not working for so many entries. Can we explore either BerkeleyDB or perhaps a NOSQL option that can still run as a flatfile indexed file?

**Comment by cjfields** [comment]
Yeah, I'm running into this as well.  A NoSQL option (maybe Neo4J) might be a good option though this will pull in additional dependencies.

**Comment by hlapp** [comment]
Or SQLite?

**Comment by cjfields** [comment]
SQLite is probably the simplest to install since the code comes with the CPAN distribution.  Will check.

**Comment by cjfields** [comment]
Just a note that I committed a short-term fix in 0c08f3393c21e that increases the page size, but this will likely only stem this temporarily.  Seems to work so far on OS X but needs testing.

**Comment by cjfields** [comment]
I have a branch where I am testing a DBD::SQLite-based version (strangely enough named Bio::DB::Taxonomy::sqlite).  It's here if anyone wants to try it out:

https://github.com/bioperl/bioperl-live/tree/topic/taxdb-to-sqlite2

**Comment by cjfields** [comment]
Merged branch in commit 5a822519.  Will likely do some additional cleanup but so far things look fine.  Tests may need tweaking, will see how Travis-CI behaves.

**Comment by cjfields** [comment]
Test

**Comment by cjfields** [comment]
Working and passing tests, will be in next release.
