### ISSUE TITLE
Current bioperl-live won't commence Build

### ISSUE THREAD

**Issue by tseemann** [bioperl/bioperl-live#102]
Just tried to build latest live 01ec10dda23b6c5ed7592808cff4ae0d34278611 and got the error below.

I have File::Copy 2.09 from Perl 5.14 (Ubuntu Server 12) but latest 2.29 is part of Perl 5.20 core which I can only force install.

````
% git clone https://github.com/bioperl/bioperl-live.git
% cd bioperl-live
% perl ./Build.PL
% ./Built test

'blib/script/bp_chaos_plot.pl' and 'blib/script/bp_chaos_plot.pl' are identical (not copied) at /usr/share/perl5/Bio/Root/Build.pm line 219
Use of uninitialized value $atime in utime at /usr/share/perl/5.14/File/Copy.pm line 393.
Use of uninitialized value $mtime in utime at /usr/share/perl/5.14/File/Copy.pm line 393.
Can't rename 'blib/script/bp_chaos_plot.pl' to 'blib/script/bp_chaos_plot.pl': No such file or directory at /usr/share/perl5/Bio/Root/Build.pm line 219.
```

**Comment by cjfields** [comment]
That's a weird one.  Does a './Build realclean' clean this up?

**Comment by tseemann** [comment]
Nope. Same error. I'm confused. Why is it running code in ```/usr/share/perl5/Bio/Root/Build.pm line 219``` ?

**Comment by cjfields** [comment]
Bio-Root is no longer included in the master branch; we're modularizing the code base.  It was removed quite a while back (2011-2012-ish) and is in a separate repo.  Seems like you have been using an older installed version?

**Comment by majensen** [comment]
B:R:Build is (or used to be) a custom subclass of M:B -- It probably has a non-standard directory layout it expects??

**Comment by tseemann** [comment]
Seems I have been using the old version for a couple of years! Whoops.

Is there a protocol for installing bioperl from git then?

**Comment by cjfields** [comment]
@tseemann at the moment we suggest using the 'v1.6.x' branch or CPAN releases for stable code, which has Bio::Root modules still with the main dist; we've been merging code fixes over from the master branch to this for CPAN releases.  

The intent is to have a 1.7 release series that will break out chunks of bioperl into separate dists (including Bio::Root modules, which can be a build dependency).
