### ISSUE TITLE
Bio::AlignIO::stockholm creates improperly formatted mark-up lines

### ISSUE THREAD

**Issue by wichne** [bioperl/bioperl-live#110]
Within the Bio::AlignIO::stockholm module, when creating the mark-up lines within `sub write_aln`, in cases where the sequence accession exceeds the arbitrary size limit of 22 characters (the [Stockholm specification] (http://sonnhammer.sbc.su.se/Stockholm.html) states "No size limits on any field"), the 'feature' text becomes joined to the 'seqname' text. This causes hmmbuild to error out.

Line 600:
```perl
my $text = sprintf("%-4s%-22s%-3s%s\n",$seq_ann,
			       $aln->displayname($seq->get_nse), $tag, $acc);
```

If:
```
$seq_ann = "#=GS "
$tag = "AC"
$acc = "accession"
$aln->displayname($seq->get_nse) = "1234567890123456789012345"
```

then:
```perl
$text = "#=GS 1234567890k123456789012345AC accession"
```

where the proper output should be:
```perl
$text = "#=GS 1234567890k123456789012345 AC accession"
```

The simple fix is to enforce spaces within the sprintf command:
Line 600:
```perl
my $text = sprintf("%-4s % -22s %-3s %s\n",$seq_ann,
			       $aln->displayname($seq->get_nse), $tag, $acc);
```

Which would yield:
```perl
$text = "#=GS  1234567890k123456789012345 AC  accession"
```
This will parse even with the extra whitespace.

Cheers,
Bill

**Comment by bosborne** [comment]
Bill,

What about the block below it, for “DR”, starting around 613? Spaces in that output as well?

Thanks again,

Brian O.

**Comment by cjfields** [comment]
@wichne @bosborne we can probably work on this one.  Does anyone want to take it on (either via a pull request or a direct commit)?

**Comment by muffato** [comment]
I think I have fixed this in the pull-request #122, which has been merged and is available on the v1.6.x branch

**Comment by cjfields** [comment]
@muffato ah, glad you pointed that out.  We'll need to pull that commit over to master.

**Comment by fjossandon** [comment]
@muffato @cjfields : The commit made to the branch in #122 is already incorporated in master:
https://github.com/bioperl/bioperl-live/commits/master/Bio/AlignIO/stockholm.pm
https://github.com/bioperl/bioperl-live/commit/a1da2c1734972a48962b815b247b8dd0473043bb

**Comment by cjfields** [comment]
@muffato Seems like @fjossandon took care of this, so closing the ticket out
