### ISSUE TITLE
Migrate HOWTOs and other docs from BioPerl wiki to bioperl.github.io

### ISSUE THREAD

**Issue by cjfields** [bioperl/bioperl-live#116]
We should have these in version control; readthedocs.org can be used to display the docs (which I believe need to be markdown).

**Comment by hyphaltip** [comment]
Could we setup a test module to begin doing this - i assume the markdown docs should just go in the same repo as the code.  We can extract all the wiki as text with some scripting. I could first check all of that into a temp repository to pull it down from. Probably with some scripts we can convert the wiki to markdown. 

I suspect all the format description and definitions of tools could be moved to wikipedia if it isn't there already?

**Comment by hlapp** [comment]
> I suspect all the format description and definitions of tools could be moved to wikipedia if it isn't there already?

That'd be great, actually!

**Comment by cjfields** [comment]
IMHO with the INSTALL docs and other important ones first, then others would be added.  Just want to mention that pandoc is great for this stuff, the hardest part will be getting the wiki dumps to text for conversion.

**Comment by cjfields** [comment]
Re: moving the other info to Wikipedia, it's related yes, but is secondary and maybe best set up as a separate task?

**Comment by cjfields** [comment]
Site is set up here (nothing under version control just yet):

http://bioperl.readthedocs.org/en/latest/

**Comment by majensen** [comment]
Why is wikipedia ideal?

On Mon, Jun 22, 2015 at 12:50 AM, Chris Fields < notifications@github.com [notifications@github.com] > wrote:
Re: moving the other info to Wikipedia, it's related yes, but is secondary and
maybe best set up as a separate task?

—
Reply to this email directly or view it on GitHub
[https://github.com/bioperl/bioperl-live/issues/116#issuecomment-113969559] .[https://github.com/notifications/beacon/AAFAmVoHl-6ijURGJ6_16QRjPgFsjGW0ks5oV0VNgaJpZM4FIE0j.gif]

**Comment by hyphaltip** [comment]
Do you mean the hardest part is extracting the text from the bioperl wiki site (there is a reasonably simple script for this which I used ages ago when setting up the template for most modules) or converting the MWiki into Markdown?  

I agree we focus on what is most important for now. I am not sure how this should interface with the API documentation and perldoc per-module?

**Comment by cjfields** [comment]
> Do you mean the hardest part is extracting the text from the bioperl wiki site (there is a reasonably simple script for this which I used ages ago when setting up the template for most modules) or converting the MWiki into Markdown?

If that's in place then the hardest part is pretty much done.  Conversion could be via Perl or using pandoc (I use the latter personally).

**Comment by hyphaltip** [comment]
Well, I cannot login to the wiki anymore as the OpenID seems broken and the user-accounts are not allowed anymore - so I can't test it, but install WWW::Mediawiki::Client and use the mvs application to checkout a wiki page as a textfile.

**Comment by bosborne** [comment]
Jason,

Very good tip. But something’s not working for me. By using that “-w” flag I’m able to construct this login URL:

http://www.bioperl.org/w/index.php?action=submitlogin&title=Special:Userlogin

But still can’t log in using mvs. Pretty sure the user and pass are correct. Is this the URL you use? Seems like this just redirects to the OpenID login page.

Thanks again,

BIO

**Comment by cjfields** [comment]
A yahoo login works for openid.  Until the MW is upgraded we're a little stuck upgrading the plugin :(.

Chris

On Jun 27, 2015, at 9:22 AM, Brian Osborne <notifications@github.com<mailto:notifications@github.com>> wrote:

Jason,

Very good tip. But something’s not working for me. By using that “-w” flag I’m able to construct this login URL:

http://www.bioperl.org/w/index.php?action=submitlogin&title=Special:Userlogin

But still can’t log in using mvs. Pretty sure the user and pass are correct. Is this the URL you use? Seems like this just redirects to the OpenID login page.

Thanks again,

BIO

**Comment by hyphaltip** [comment]
Folks - who can we get to take charge of this?
I'm sorry I won't be at the conference this summer to help discuss this. 
I think it is important to consolidate and simplify the web presence so we can at least make an effort to keep it up to date and modern. Maybe we can establish a todo list for the website and go through efforts it will take for this?

Realistically who do we have that can put any time into development? Let's commit some people hours to this this summer so we can get this next release out and include an update to the websites.

**Comment by cjfields** [comment]
@hyphaltip I can help steer direction and some dev but we need contribution from others as well.  A basic roadmap would be a good idea to focus direction and split up priorities; @majensen and I discussed this previously.  It's easy to add new issues and assign them to roadmaps here.

@bosborne the only OpenID provider working at the moment with the current plugin is Yahoo, and I don't expect that to last indefinitely.  We need to prioritize MW upgrades, but no one has been willing to tackle this due to the installation.  This would also help the other Bio* and main OBF wikis, BTW, so we can go outside the bioperl community if needed, but again no one wants to tackle this in case of breakage.  

@hyphaltip any idea how to best move forward here?  Or is this something that Chris D. should do?

**Comment by majensen** [comment]
I can dedicate some tuits to this @cjfields, if u can task me

On Thu, Jul 09, 2015 at 10:54 AM, Chris Fields < notifications@github.com [notifications@github.com] > wrote:
@hyphaltip [https://github.com/hyphaltip] I can help steer direction and some dev but we need contribution from others as
well. A basic roadmap would be a good idea to focus direction and split up
priorities; @majensen [https://github.com/majensen] and I discussed this previously. It's easy to add new issues and assign them to
roadmaps here.

@bosborne [https://github.com/bosborne] the only OpenID provider working at the moment with the current plugin is
Yahoo, and I don't expect that to last indefinitely. We need to prioritize MW
upgrades, but no one has been willing to tackle this due to the installation.
This would also help the other Bio* and main OBF wikis, BTW, so we can go
outside the bioperl community if needed, but again no one wants to tackle this
in case of breakage.

@hyphaltip [https://github.com/hyphaltip] any idea how to best move forward here? Or is this something that Chris D.
should do?

—
Reply to this email directly or view it on GitHub
[https://github.com/bioperl/bioperl-live/issues/116#issuecomment-120013613] .[https://github.com/notifications/beacon/AAFAmXiEbS_8IPO2XgfGQTfDnKVDjOKOks5oboLmgaJpZM4FIE0j.gif]

**Comment by cjfields** [comment]
Looks like this is somewhat underway, what that you @majensen? @bosborne?

http://bioperl.readthedocs.org/en/latest/#a-simple-module-summary

My github notifications seem to be fubar'd (not getting proper notifications from bioperl-live but getting them from other repos).  So, if I don't reply immediately don't take it as a sign to hold, please feel free to proceed :+1:

**Comment by majensen** [comment]
Wow,not me but prob I can be helping. Thanks to the anonymous Samaritan

On Sat, Oct 17, 2015 at 10:19 AM, Chris Fields < notifications@github.com [notifications@github.com] > wrote:
Looks like this is somewhat underway, what that you @majensen [https://github.com/majensen] ? @bosborne [https://github.com/bosborne] ?

http://bioperl.readthedocs.org/en/latest/#a-simple-module-summary
[http://bioperl.readthedocs.org/en/latest/#a-simple-module-summary]

My github notifications seem to be fubar'd (not getting proper notifications
from bioperl-live but getting them from other repos). So, if I don't reply
immediately don't take it as a sign to hold, please feel free to proceed:+1: [https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png]

—
Reply to this email directly or view it on GitHub
[https://github.com/bioperl/bioperl-live/issues/116#issuecomment-148918649] .[https://github.com/notifications/beacon/AAFAmSXLsfpSlxNLQ2gFNdmxwWMeIsIwks5o8lCvgaJpZM4FIE0j.gif]

**Comment by cjfields** [comment]
I think it is pulling straight from the README.md as a default (so we probably stumbled into doing the right thing).  What we may want to do is convert MW -> POD or MD for the repo.

On Oct 17, 2015, at 9:22 AM, Mark Jensen <notifications@github.com<mailto:notifications@github.com>> wrote:

Wow,not me but prob I can be helping. Thanks to the anonymous Samaritan

On Sat, Oct 17, 2015 at 10:19 AM, Chris Fields < notifications@github.com<mailto:notifications@github.com> [notifications@github.com<mailto:notifications@github.com>] > wrote:
Looks like this is somewhat underway, what that you @majensen [https://github.com/majensen] ? @bosborne [https://github.com/bosborne<https://github.com/majensen]%20?%20@bosborne%20[https://github.com/bosborne>] ?

http://bioperl.readthedocs.org/en/latest/#a-simple-module-summary
[http://bioperl.readthedocs.org/en/latest/#a-simple-module-summary]

My github notifications seem to be fubar'd (not getting proper notifications
from bioperl-live but getting them from other repos). So, if I don't reply
immediately don't take it as a sign to hold, please feel free to proceed:+1: [https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png]

—
Reply to this email directly or view it on GitHub
[https://github.com/bioperl/bioperl-live/issues/116#issuecomment-148918649] .[https://github.com/notifications/beacon/AAFAmSXLsfpSlxNLQ2gFNdmxwWMeIsIwks5o8lCvgaJpZM4FIE0j.gif<https://github.com/bioperl/bioperl-live/issues/116#issuecomment-148918649]%20.[https://github.com/notifications/beacon/AAFAmSXLsfpSlxNLQ2gFNdmxwWMeIsIwks5o8lCvgaJpZM4FIE0j.gif>]

**Comment by bosborne** [comment]
All,

So I’ve written a little converter that uses pandoc to convert Wiki pages to markdown. Unfortunately when the input is HTML, for example from a HOWTO page, the resulting markdown is very low quality. My suspicion is that the best way is to start with MediaWiki markup, not HTML. 

Can we simply inactivate the OpenID extension for some short period of time? Then this script can login and get MW markup, convert to Markdown of some kind.

Brian O.

**Comment by carandraug** [comment]
@bosborne said:
> [...]
> Can we simply inactivate the OpenID extension for some short period of time? Then this script can login and get MW markup, convert to Markdown of some kind.

Why do you need to be able to login to get the mediawiki markup? You can simply add `?action=raw` at any page to get the raw page.  For example, [http://www.bioperl.org/wiki/HOWTO:Beginners?action=raw](http://www.bioperl.org/wiki/HOWTO:Beginners?action=raw)

I have used the following before:

    use LWP::Simple; 
    my $wiki = 'http://www.bioperl.org/wiki/HOWTO:Beginners';
    my $source = get ("$wiki?action=raw");

**Comment by bosborne** [comment]
I guess the answer is “that’s how I wrote my script”!

OK, let’s do rewrite, do “raw” ...

**Comment by bosborne** [comment]
OK, so way back in beginning of this thread various points were made:

- OpenID is an issue
- we can script the conversion of Wiki pages to Markdown
- we can "check all of that into a temp repository to pull it down from”, meaning all of the Markdown text, converted from the Wiki.

So it turns out that OpenID is not an issue, and that we can convert Wiki pages to Markdown, specifically GitHub Markdown. It looks like we want this flavor of Markdown since it supports tables, plain Markdown does not, and there are plenty of tables in our Wiki pages. There are flaws in the pandoc conversion, but nothing that a few regular expressions couldn’t fix, IMO.

There’s been an assumption that we put all of this into readthedocs.org. Why? Why don’t we just use a GitHub Wiki, all the codes and tickets (thank you Chris) are in GitHub now? In addition, once a GitHub Wiki is set up it can be set up to automatically create pages in readthedocs:

https://github.com/rtfd/readthedocs.org

In fact, looks like someone has already set us up for this, our Good Samaritan.

Let’s make a decision, GitHub Wiki versus readthedocs. I vote for GitHub Wiki, and we get a readthedocs site for free. Also, pandoc converts to GitHub Markdown.

Your thoughts or votes?

**Comment by hlapp** [comment]
> On Oct 17, 2015, at 5:58 PM, Brian Osborne <notifications@github.com> wrote:
> 
> There’s been an assumption that we put all of this into readthedocs.org <http://readthedocs.org/>. Why? Why don’t we just use a GitHub Wiki, all the codes and tickets (thank you Chris) are in GitHub now? In addition, once a GitHub Wiki is set up it can be set up to automatically create pages in readthedocs:
> 
> https://github.com/rtfd/readthedocs.org <https://github.com/rtfd/readthedocs.org>
> 
> In fact, looks like someone has already set us up for this, our Good Samaritan.
> 
> Let’s make a decision, GitHub Wiki versus readthedocs. I vote for GitHub Wiki, and we get a readthedocs site for free. Also, pandoc converts to GitHub Markdown.
> 
> Your thoughts or votes?

Note that there is another option, Github Pages markdown. I would actually vote for that. It would allow anyone with a Github account to contribute, watch, and review using regular pull requests of edits to markdown text documents. And we have lots of possibilities for branding and theming, using available themes for Jekyll (or another static page generator if we wanted to do that - there are ones in Perl, Python, Java, JavaScript, etc ).

  -hilmar

-- 
Hilmar Lapp -:- lappland.io

**Comment by cjfields** [comment]
The main reason (IMHO) to convert some docs for ReadTheDocs is to have some of the relevant docs versioned along with the code.  A wiki would only have the most up-to-date version.

On Oct 17, 2015, at 5:52 PM, Hilmar Lapp <notifications@github.com<mailto:notifications@github.com>> wrote:
...

Note that there is another option, Github Pages markdown. I would actually vote for that. It would allow anyone with a Github account to contribute, watch, and review using regular pull requests of edits to markdown text documents. And we have lots of possibilities for branding and theming, using available themes for Jekyll (or another static page generator if we wanted to do that - there are ones in Perl, Python, Java, JavaScript, etc ).

-hilmar

--
Hilmar Lapp -:- lappland.io<http://lappland.io>

**Comment by cjfields** [comment]
@hlapp Ah yes, GH Pages is a good option (I would suggest this over the wiki).

**Comment by tsibley** [comment]
For what it's worth, in case it's not widely known: GitHub wikis are also git repositories, with their own git URL, and you can check them out and make edits and push/pull just as you would any other git repo.  You can also edit them directly on the web.  More information: https://help.github.com/articles/adding-and-editing-wiki-pages-locally/

One difference between GitHub Pages and GitHub Wikis is that Pages are on a `gh-pages` orphan branch inside your normal repo and Wikis are a separate repo.  Other than that, the differences come down to appearance and user experience.

**Comment by bosborne** [comment]
All,

GitHub Wiki or GitHub Pages? Have we made a decision? I have no preference myself.

Thanks again,

BIO

**Comment by bosborne** [comment]
All,

I’ve created a repository for the BioPerl GitHub Pages site:

https://github.com/bioperl/bioperl.github.io <https://github.com/bioperl/bioperl.github.io>

Nothing there yet. I wrote a script to download HOWTO’s (or any other page), convert them to GitHub Markdown. Works OK, but some manual edits will still be required.

Brian O.

**Comment by cjfields** [comment]
@bosborne Awesome work!  May as well run the conversion, it will be hard to get away from some manual editing.  We had the same problem IIRC when we converted from POD to Mediawiki markup.

**Comment by hyphaltip** [comment]
Yeah. This is great Brian. These could use some touch ups too so good
excuse to revisit.

**Comment by bosborne** [comment]
All,

Did the required tinkering, now we have the basics of a new site, using GitHub Pages with Jekyll:

https://bioperl.github.io <https://bioperl.github.io/>

Details:

- the content is in this repository: https://github.com/bioperl/bioperl.github.io <https://github.com/bioperl/bioperl.github.io>
- GitHub Markdown can be used: https://help.github.com/articles/github-flavored-markdown/ <https://help.github.com/articles/github-flavored-markdown/>
- Jekyll is Ruby, so much of the work is done by embedded Ruby, and it is not based on Rails, it’s simpler
- Jekyll converts all Markdown files and copies them to the _site/ directory where they are served up, but only if they have headers like this:

---
title: "HOWTO:AlignIO and SimpleAlign"
layout: default
---

Notes:

- we can use a theme, the themes are here: http://jekyllthemes.org
- all HOWTO’s have been copied over, and all require some editing
- stating the obvious: there are many more pages left in the Wiki
- many of these pages can - or should - be left in the Wiki, and not migrated over, they are outdated or extraneous
- at some point we’ll take down the Wiki and point this site to bioperl.org

Personally I think copying all pages over in a scripted manner would be a bad idea.

I don’t intend to edit all the HOWTO’s, probably just the ones I wrote or co-wrote. And more content can be copied over. pandoc can be used to convert MediaWiki markup or HMTL to GitHub Markdown (though the conversion is not flawless).

We need volunteers - who is interested in helping out?

Brian O.

**Comment by pcantalupo** [comment]
Hi Brian,

I would like to help. Do you want me to pick a HOWTO and proofread and test each code element?

**Comment by cjfields** [comment]
@pcantalupo @bosborne I added the BioPerl developers and core teams to the bioperl,github.io repo.  If we have too many folks working on revisions it may cause problems; maybe set up issues on that repo and have devs note which docs they're working on?  It would prevent replication of effort...

**Comment by bosborne** [comment]
Paul,

Yes, but I would say just proofread to correct the conversion errors. There are stray characters, “run on” code blocks, things like that. Sometimes it takes a minute or 2 for your edits to show up in the GitHub pages site. Checkout the repo, use your editor, or edit directly in GitHub.

And you can look at the Wiki, copy any pages over that you think are important.

Your help is appreciated!

Brian O.

**Comment by bosborne** [comment]
Paul and Chris,

I will proofread Beginners, SearchIO, SeqIO.

Paul, which will you take?

Other authors or proofreaders? Just talking about the HOWTOs.

Brian O.

**Comment by cjfields** [comment]
I can take a few, would probably start with EUtilities but can also have a look at others (will start with 3 or so).  I'll set up an issue on the github.io tracker for this.

I think we have a remedial page for readthedocs up, I may have it redirect to the github.io pages if possible.

**Comment by pcantalupo** [comment]
i'll start with BlastPlus right now

**Comment by majensen** [comment]
I'll take my stuff, tiling in particular, and look around for other items I
could help on
Mark

On Mon, Nov 30, 2015 at 10:45 AM, Chris Fields < notifications@github.com [notifications@github.com] > wrote:
I can take a few, would probably start with EUtilities but can also have a look
at others (will start with 3 or so). I'll set up an issue on the github.io
tracker for this.

I think we have a remedial page for readthedocs up, I may have it redirect to
the github.io pages if possible.

—
Reply to this email directly or view it on GitHub
[https://github.com/bioperl/bioperl-live/issues/116#issuecomment-160666922] .[https://github.com/notifications/beacon/AAFAmQMinpOdaAgdRRv6O4LwvMZAOryMks5pLGbrgaJpZM4FIE0j.gif]

**Comment by bosborne** [comment]
All,

Some technical notes:

- the Markdown is making tables, but they don’t look great since there are no borders, I think the fix is editing the CSS, somewhere
- if you clone the repo you can launch the site locally, something like:

gem install jekyll
cd bioperl.github.io
jekyll serve --baseurl ''

Then open http://localhost:4000 <http://localhost:4000/> in the browser.

Easier and quicker than editing, committing, pushing, and waiting for http://bioperl.github.io <http://bioperl.github.io/>.

Brian O.

**Comment by cjfields** [comment]
Ticket started on tracking who's doing what on HOWTOs:

https://github.com/bioperl/bioperl.github.io/issues/1

Should we move the discussion there?

**Comment by bosborne** [comment]
All,

A note for those editing the HOWTO Markdown. To link to another HOWTO do this:

[Feature-Annotation HOWTO](Feature-Annotation.html)

Not this:

[Feature-Annotation HOWTO](Feature-Annotation.md)

The reason is that Jekyll finds all Markdown files, converts them to HTML, and puts the HTML into _site/, everything that’s served out of this dir is HTML.

BIO

**Comment by bosborne** [comment]
All,

Added the converted sequence, alignment, and tree format pages from the Wiki. Think these have some utility.

Brian O.

**Comment by bosborne** [comment]
All,

This work is essentially complete, every HOWTO has been converted to Markdown and edited. Also, what was “Advanced BioPerl” is now a HOWTO.

A special shout-out has to go to Paul Cantalupo, he did the Lion’s Share of the work.

There are a number of tasks that remain:

https://github.com/bioperl/bioperl.github.io/issues <https://github.com/bioperl/bioperl.github.io/issues>

And I’m not claiming this list is complete.

Also bear in mind that we are not wedded to the existing theme, we can modify it of course, and alternative Jekyll themes are available:

http://jekyllthemes.org <http://jekyllthemes.org/>

Some of these have search capability built-in.

Brian O.

**Comment by aleimba** [comment]
even though I can't find time to help out: fantastic work guys, thanks a lot!

**Comment by bosborne** [comment]
Done

**Comment by cjfields** [comment]
Thx @bosborne !
