### ISSUE TITLE
Bug in _codon_is method of Bio/Tools/CodonTable.pm file

### ISSUE THREAD

**Issue by Juke34** [bioperl/bioperl-live#118]
The for loop doesn't check all the codons possible of " $self->unambiguous_codons($value)" list but only the first one due to the return statement. 
Example: Using the codon "AYG" will give you the list (ACG ATG) but only ACG will be tested and the method will return 0.

*Instead of:*

sub _codon_is {
   my ($self, $value, $table, $key ) = @_;

   return 0 unless length $value == 3;

   $value  = lc $value;
   $value  =~ tr/u/t/;

   my $id = $self->{'id'};
   for my $c ( $self->unambiguous_codons($value) ) {
       my $m = substr( $table->[$id], $CODONS->{$c}, 1 );
       return 0 unless $m eq $key;
   }
   return 1;
}

*We should write:*

sub _codon_is {
   my ($self, $value, $table, $key ) = @_;

   return 0 unless length $value == 3;

   $value  = lc $value;
   $value  =~ tr/u/t/;

   my $id = $self->{'id'};
   for my $c ( $self->unambiguous_codons($value) ) {
       my $m = substr( $table->[$id], $CODONS->{$c}, 1 );
      **if ($m eq $key) { return 1; }**
   }
  **return 0;**
}

**Comment by pcantalupo** [comment]
Hello,
Nice catch. I checked this by adding an `is_start_codon('AYG')` to the test file `t/SeqTools/CodonTable.t` as expected, it fails. To get this updated, create a pull request with your fix and reference this issue # in the commit message.

**Comment by cjfields** [comment]
Assuming this bug is fixed, so closing issue.
