### ISSUE TITLE
parsing hmmer results: rare situation causes parsing failure

### ISSUE THREAD

**Issue by jayoung** [bioperl/bioperl-live#119]
Hi there,

I've just started playing with parsing some hmmer output files (hmmsearch), and have run across a rare situation that causes the parser to choke.  I think the issue arises where the subject sequence has a stop codon that gets wrapped to the first position in an alignment row. Stop codons in the middle of a row seem to do just fine.  Hopefully it'll be easy to fix. I updated my Bioperl a few minutes ago using git.

I've attached a screenshot of the alignment, and will see if I can attach the full hmmer output file here. 

I'm parsing with a very simple script for now that looks like this:
#!/usr/bin/perl
use Bio::SearchIO;
my $hmmerIN = Bio::SearchIO->new(-file => "< ORF1align4.edit.fa.hmm.hmmsearchVSproblemSeq", -format => "hmmer");
while( my $result = $hmmerIN->next_result ) {
    print $result->query_name(), " for HMM ", $result->hmm_name(), "\n";
}

and it crashes on this particular alignment with this: error
Quantifier follows nothing in regex; marked by <-- HERE in m/* <-- HERE E-IWDYVKRPNLRLIGVPESDVENGTKLENTLQDIIQENFPNLARQANVQIQEIQRTPQRYSSRRATPRHIIVR/ at /home/jayoung/malik_lab_shared/perl/bioperl-live/Bio/SearchIO/hmmer3.pm line 721, <GEN2> line 39.

![temp](https://cloud.githubusercontent.com/assets/2569397/9373323/19064e3a-469e-11e5-8917-05dbdf8b436d.png)

all the best,

Janet Young

------------------------------------------------------------------- 

Dr. Janet Young 

Malik lab
http://research.fhcrc.org/malik/en.html

Fred Hutchinson Cancer Research Center
1100 Fairview Avenue N., A2-025, 
P.O. Box 19024, Seattle, WA 98109-1024, USA.

tel: (206) 667 4512
email: jayoung  ...at...  fhcrc.org

-------------------------------------------------------------------

**Comment by jayoung** [comment]
Can't see a way to attach the file, so I'll copy-paste it in as a separate comment - here it comes

**Comment by jayoung** [comment]
# hmmsearch :: search profile(s) against a sequence database
# HMMER 3.1b2 (February 2015); http://hmmer.org/
# Copyright (C) 2015 Howard Hughes Medical Institute.
# Freely distributed under the GNU General Public License (GPLv3).
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# query HMM file:                  /home/jayoung/FH_fast_storage/repeats/getFullLengthElementsFromGenomes/getORF1referenceAlignment/alignment/ORF1align4.edit.fa.hmm
# target sequence database:        chr2_178837800-178843817_+_.fa.peps.fasta
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Query:       ORF1aln4  [M=340]
Scores for complete sequences (score includes all domains):
   --- full sequence ---   --- best 1 domain ---    -#dom-
    E-value  score  bias    E-value  score  bias    exp  N  Sequence                           Description
    ------- ------ -----    ------- ------ -----   ---- --  --------                           -----------
   1.2e-128  416.5  23.3   1.2e-128  416.5  23.3    2.4  2  chr2:178837800-178843817(+).fr1pep  


Domain annotation for each sequence (and alignments):
>> chr2:178837800-178843817(+).fr1pep  
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !  416.5  23.3  4.1e-129  1.2e-128       1     339 [.     303     637 ..     303     638 .. 0.98
   2 ?    0.0  12.5     0.019     0.056      36     137 ..     942    1054 ..     918    1094 .. 0.49

  Alignments for each domain:
  == domain 1  score: 416.5 bits;  conditional E-value: 4.1e-129
                            ORF1aln4   1 mgkkqrkksentkkqekspekkeqksspeeeekikeeeilelseeefkkiilkllkeleeelekekkevieklee 75 
                                         mgkkq++k++n+k+q++sp+ ke++ssp++e++++e++++el+ee f++   ++++el+e+++++ kev e+ e+
  chr2:178837800-178843817(+).fr1pep 303 MGKKQNRKTGNSKTQSASPPPKERSSSPATEQSWMENDFDELREEGFRR---SNYSELREDIQTKGKEV-ENFEK 373
                                         99***********************************************...78889999999999998.8999* PP

                            ORF1aln4  76 kleklekeieeiekklkelkeikkkieeikneleslknrieelEerisdledkleeikeeekesekrikkneesl 150
                                         +le++ ++i+++ek+lkel+e+k+k++e+++e++sl++r+++lEer+s++ed+++e+k+e k +ek+ik+ne+sl
  chr2:178837800-178843817(+).fr1pep 374 NLEECITRITNTEKCLKELMELKTKARELREECRSLRSRCDQLEERVSAMEDEMNEMKREGKFREKIIKRNEQSL 448
                                         *************************************************************************97 PP

                            ORF1aln4 151 .relsdtikrnNlriiGvpEeeeekekglenileeilkenFPnlkkeeeiqiqeaqRtPnrlnqkrktpRHiivk 224
                                            ++d++kr+Nlr+iGvpE++ e+ ++len+l++i++enFPnl++++++qiqe+qRtP+r++++r+tpRHiiv+
  chr2:178837800-178843817(+).fr1pep 449 *E-IWDYVKRPNLRLIGVPESDVENGTKLENTLQDIIQENFPNLARQANVQIQEIQRTPQRYSSRRATPRHIIVR 522
                                         77.9*********************************************************************** PP

                            ORF1aln4 225 ltkvkeKekiLkaarekkqvtykGkpirltaDlSaetlqarreWsdifqvLkeknlqPRilYPakLSfkidgeik 299
                                         +tkv++Kek+L+aarek++vt+kGkpirltaDlSaetlqarreW +if++Lkekn+qPRi YPakLSf ++geik
  chr2:178837800-178843817(+).fr1pep 523 FTKVEMKEKMLRAAREKGRVTLKGKPIRLTADLSAETLQARREWGPIFNILKEKNFQPRISYPAKLSFISEGEIK 597
                                         *************************************************************************** PP

                            ORF1aln4 300 vFtdkqkLkefvktkPaLqeiLkdalqeeeqnsakkkkrk 339
                                         +F dkq+L++fv+t+PaL+e+Lk+al++e++n+++  +++
  chr2:178837800-178843817(+).fr1pep 598 YFIDKQMLRDFVTTRPALKELLKEALNMERNNRYQPLQNH 637
                                         **********************************999886 PP

  == domain 2  score: 0.0 bits;  conditional E-value: 0.019
                            ORF1aln4   36 eeeilelseeefkkiilkllkeleeelekekkeviekl.........eekleklekeieeiekklkelke..i 97  
                                          ++++ +  ++ fk ++  ++  l+  ++k++++ i +l         +e++++  ++ +ei+k  +elke  +
  chr2:178837800-178843817(+).fr1pep  942 KDTTYQNLWDAFKAVCRGKFIALNAYKRKQERSKIDTLtsqlkelekQEQTHSKASRRQEITKIRAELKEieT 1014
                                          4445555566777777777777774444444444444411111111122222222223333333333333333 PP

                            ORF1aln4   98 kkkieeikneleslknrieelEerisdledkleeikeeek 137 
                                          +k+++ i+++ + + +ri++++  ++ l +k  e+++  +
  chr2:178837800-178843817(+).fr1pep 1015 QKTLQKINESRSWFFERINKIDRPLARLIKKKREKNQIDT 1054
                                          4444444444444445555554444444444444333332 PP



Internal pipeline statistics summary:
-------------------------------------
Query model(s):                              1  (340 nodes)
Target sequences:                            3  (6015 residues searched)
Passed MSV filter:                         1  (0.333333); expected 0.1 (0.02)
Passed bias filter:                        1  (0.333333); expected 0.1 (0.02)
Passed Vit filter:                         1  (0.333333); expected 0.0 (0.001)
Passed Fwd filter:                         1  (0.333333); expected 0.0 (1e-05)
Initial search space (Z):                  3  [actual number of targets]
Domain search space  (domZ):               1  [number of targets reported over threshold]
# CPU time: 0.01u 0.00s 00:00:00.01 Elapsed: 00:00:00.01
# Mc/sec: 204.51
//
[ok]

**Comment by pcantalupo** [comment]
Does your patch pass all the bioperl tests? If so, create a pull request.

**Comment by jayoung** [comment]
I don't have a patch - just a bug report. Sorry!

**Comment by sestaton** [comment]
Hi Janet, 

Can you try to attach the file again? I think this is a new github feature that may not have been available before. That would make it easier to reproduce the error than trying to copy the above report.

**Comment by jayoung** [comment]
Hi there,

Sorry it took me a month to get back to you on this.  I just tried attaching the file, but no luck: "Attaching documents requires write permission to this repository.  Try again with a PNG, GIF, or JPG."  It's a plain text file (before I added .txt to my non-standard name, I got a different error, that the file type was not supported). I'm happy to email the file to whoever wants it, or maybe someone can get me write permission?

thanks,

Janet

**Comment by pcantalupo** [comment]
@jayoung maybe post the file as a [gist] (https://gist.github.com)

**Comment by jayoung** [comment]
https://gist.github.com/jayoung/f7230a83410518d0bc24.js

**Comment by jayoung** [comment]
https://gist.github.com/jayoung/f7230a83410518d0bc24#file-gistfile1-txt

**Comment by jayoung** [comment]
Thanks, @pcantalupo - I think that worked.

**Comment by pcantalupo** [comment]
closing based on Francisco's fix in b5e68c7

**Comment by fjossandon** [comment]
Oh, I didn't realize that we stumbled on the same bug. Thanks for closing Paul!

**Comment by jayoung** [comment]
Thanks for the fix - much appreciated.
