### ISSUE TITLE
Build.pm absent

### ISSUE THREAD

**Issue by chjp** [bioperl/bioperl-live#120]
perl Build.PL
Can't locate Bio/Root/Build.pm in @INC (@INC contains: ./bin/bioperl-live etc)

**Comment by majensen** [comment]
At the moment, you will need to pull down
https://github.com/bioperl/Bio-Root
to satisfy this dep.

**Comment by cjfields** [comment]
Bio-Root has been merged back in to the master branch, so this issue should be resolved.
