### ISSUE TITLE
Problem with newer versions of AlignIO to write alignment data

### ISSUE THREAD

**Issue by franciscolobo** [bioperl/bioperl-live#123]
Dear bioperl folks,

I have been using bioperl for a while to develop POTION, an end-to-end pipeline to detect positive selection in coding sequence data. POTION uses Bioperl to do a lot of things regarding handling sequence/alignment data. Im particular, POTION users AlignIO to change the format of alignment data from phylip to fasta and vice-versa.

When testing POTION using a somewhat older version of BioPerl (1.006901) it works just fine. However, when I updated Bioperl to a newer version (1.006923) POTION stopped working and got stuck when using AlignIO to write alignment objects.

I wrote a very simple code (pasted below) that works just fine when using BioPerl (1.006901) (it finishes after less than a second and correctly writes the output file in fasta format), but it gets stuck when using newer versions of Bioperl (I tested 1.006923 and 1.006924). Please let me know if I can help you to fix this bug.

```perl
use strict;
use warnings;
use Bio::AlignIO;

my $infile = $ARGV[0];

chomp $infile;

my $in  = Bio::AlignIO->new(-file => "$infile" ,
                                             -format => 'phylip');


my $out = Bio::AlignIO->new(-file => ">$infile.fa",
                                              -format => 'fasta');

while (my $aln = $in->next_aln ) {
  $out->write_aln($aln);
}
```

**Comment by pcantalupo** [comment]
Hello,

Can you create a Gist post of a minimal version of your input file that recreates the problem? Thank you

**Comment by bosborne** [comment]
Francisco, 

Please upload an input file that will show this bug, $infile in the example above.

**Comment by franciscolobo** [comment]
Please find the example file below.

[ORTHOMCL2345.cluster.aa.fa.aln.aa.phy.txt](https://github.com/bioperl/bioperl-live/files/242700/ORTHOMCL2345.cluster.aa.fa.aln.aa.phy.txt)
