### ISSUE TITLE
Bio::SeqIO::embl parsing DT lines: regex fails to catch release update number.

### ISSUE THREAD

**Issue by hdevillers** [bioperl/bioperl-live#126]
In the package Bio::SeqIO::embl the two regex lines 305 and 311 may have ambiguous modifiers. The aim of these regex is to parse the DT lines from embl files, for example:
DT   29-SEP-2015 (Rel. 1, Created)
DT   29-SEP-2015 (Rel. 1, Last updated, Version 1)

the two regex use the xms modifiers. The modifier x implies the protection of whitespace characters in the regex. This is not the case in the two regex line 305 and 311:
if ($version =~ /\(Rel\. (\d+), Created\)/xms ) => is always false.

Thus the modifier x should be removed (I am not convinced by the interest of modifiers ms too) or it can be kept by adding backslashes before all whitespaces.

**Comment by cjfields** [comment]
@hdevillers I think this was added in a pique of adapting Perl Best Practices but the space issue wasn't fixed (so you are correct, they should be explicit or escaped).  The 'ms' modifier was considered a best practice for single-line (from `perlre`):

> Used together, as /ms, they let the "." match any character whatsoever, while still allowing "^" and "$" to match, respectively, just after and just before newlines within the string.

Care to submit a pull request?  Always a good way to get involved in the project :smiley:

**Comment by cjfields** [comment]
Fixed per pull request, thanks @hdevillers for reporting
