### ISSUE TITLE
Problems with running bp_genbank2gff3.pl

### ISSUE THREAD

**Issue by areejalsheikh** [bioperl/bioperl-live#127]
Hi,

Here is the error I keep getting whenever I run this script:

```Can't locate YAML.pm in @INC (@INC contains: blib/lib /Users/Areej/bioperl-live /sw/lib/perl5 /sw/lib/perl5/darwin /Library/Perl/5.16/darwin-thread-multi-2level /Library/Perl/5.16 /Network/Library/Perl/5.16/darwin-thread-multi-2level /Network/Library/Perl/5.16 /Library/Perl/Updates/5.16.2/darwin-thread-multi-2level /Library/Perl/Updates/5.16.2 /System/Library/Perl/5.16/darwin-thread-multi-2level /System/Library/Perl/5.16 /System/Library/Perl/Extras/5.16/darwin-thread-multi-2level /System/Library/Perl/Extras/5.16 .) at /usr/local/bin/bp_genbank2gff3.pl line 224.
BEGIN failed--compilation aborted at /usr/local/bin/bp_genbank2gff3.pl line 224.```

I tried installing YAML but it didn't help.

Thanks,
Areej

**Comment by jhannah** [comment]
Hi Areej, how did you install YAML? If YAML is installed you shouldn't get that error any more. I usually use http://perlbrew.pl/ to control my local Perl environments, and `perlbrew install-cpanm` to get `cpanm`, which is the tool I use to install Perl dependencies like YAML. Can you show us (in gist.github.com or whatever) how you installed YAML, and all the output that occurred when you did?

**Comment by areejalsheikh** [comment]
Hi jhanna,

Thanks for your reply. I don't user perlbrew, and I had cpanm installed (I use MacOSX and homebrew). This is how I installed YAML:

```sudo cpanm YAML::XS                
Password:
--> Working on YAML::XS
Fetching http://www.cpan.org/authors/id/I/IN/INGY/YAML-LibYAML-0.59.tar.gz ... OK
Configuring YAML-LibYAML-0.59 ... OK
Building and testing YAML-LibYAML-0.59 ... OK
Successfully installed YAML-LibYAML-0.59
1 distribution installed``` 

I'm worried that I broke perl in my system altogether! Do you reckon perlbrew can help put it back in place? 

Thanks,
Areej

**Comment by majensen** [comment]
I think if you go ahead and in YAML (alongside YAML::XS), it may solve the
problem. I believe YAML will delegate to YAML::XS when it's available, so you
shouldn't see a performance issue.
Does this make any sense? MAJ

On Tue, Oct 20, 2015 at 7:32 PM, Areej Alsheikh-Hussain < notifications@github.com [notifications@github.com] > wrote:
Hi jhanna,

Thanks for your reply. I don't user perlbrew, and I had cpanm installed (I use
MacOSX and homebrew). This is how I installed YAML:

sudo cpanm YAML::XS
Password:
--> Working on YAML::XS
Fetching http://www.cpan.org/authors/id/I/IN/INGY/YAML-LibYAML-0.59.tar.gz ...
OK
Configuring YAML-LibYAML-0.59 ... OK
Building and testing YAML-LibYAML-0.59 ... OK
Successfully installed YAML-LibYAML-0.59
1 distribution installed

I'm worried that I broke perl in my system altogether! Do you reckon perlbrew
can help put it back in place?

Thanks,
Areej

—
Reply to this email directly or view it on GitHub
[https://github.com/bioperl/bioperl-live/issues/127#issuecomment-149734763] .[https://github.com/notifications/beacon/AAFAmeUT52bGDVhO-Gl0O74Bry7fp519ks5o9sbCgaJpZM4GRzly.gif]

**Comment by areejalsheikh** [comment]
Didn't realise they're different, thank you very much. I installed it and now the script works :+1:  
Cheers,
Areej

**Comment by majensen** [comment]
Awesome! YAML::XS is written in large part directly in C, and so is faster
(presumably). YAML is smart enough to know when you have it installed and use
it...but it doesn't work the other way round.
Cheers
MAJ

On Tue, Oct 20, 2015 at 9:24 PM, Areej Alsheikh-Hussain < notifications@github.com [notifications@github.com] > wrote:
Didn't realise they're different, thank you very much. I installed it and now
the script works:+1: [https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png]

Cheers,
Areej

—
Reply to this email directly or view it on GitHub
[https://github.com/bioperl/bioperl-live/issues/127#issuecomment-149752302] .[https://github.com/notifications/beacon/AAFAmQJMVjw6ul3dFOIz1zDM6wELGtxnks5o9uDmgaJpZM4GRzly.gif]

**Comment by cjfields** [comment]
Assuming this is closed?

**Comment by majensen** [comment]
Oh yes, close away...
