### ISSUE TITLE
Bio::SearchIO::hmmer3.pm writing unparsable lines to stdout

### ISSUE THREAD

**Issue by JoeCarlson** [bioperl/bioperl-live#129]
Hello,

Thanks for all the work.

I've just run into a minor annoyance: When Bio::SearchIO::hmmer3.pm finds a line that it cannot parse, it writes that line to stdout along with the message 'Missed this line:' Lines 622 and 768 from the source code are examples.

This is messing up my downstream parsing. Can this to redirected to stderr or somehow treated better?

The particular lines that is causing problems are from hmmscan 3.1b1 which looks like:

>> 2fo7A00
[No individual domains that satisfy reporting thresholds (although complete target did)]

I can deal with it in my local copy, but this seems like something that should be handled differently.

**Comment by cjfields** [comment]
@JoeCarlson unfortunately issues like this are harder to debug w/o a test case.  Can you attach a text file (extension `.txt`), using the 'Attach files' option (will be under the text box when you reply)?  Alternatively, if you have a bug fix we gladly accept patches or pull requests.

**Comment by JoeCarlson** [comment]
I've attempted to attach files to the issue, but I'm getting a message: 
"Attaching documents requires write permission to this repository"

The files are simple enough that I can attached them in this message, if 
that's good enough.

I've attached 2 files: pfamExample.out (result of running hmmscan of 1 
sequence against pfam-a) and hmmToSSF (a perl script that convets to sam 
summary file format.

hmmToSSF < pfamExample.out

results in:
Missed this line:    [No individual domains that satisfy reporting 
thresholds (although complete target did)]

273647885    PF00013.25    424    0    0    0    155    208    56 55    
4.1e-14    40.0    0    1    155:208
273647885    PF00013.25    424    0    0    0    247    312    62 61    
4.9e-16    46.1    0    1    247:312
273647885    PF13014.2    424    0    0    0    164    203    43 42    
1.5e-13    38.1    0    1    164:203
273647885    PF13014.2    424    0    0    0    255    301    1 43    
4.7e-13    36.6    0    1    255:301

It would be "nice" if the printing of unparsable line could go to 
STDERR, or to update the parser to handle these cases. It can be safely 
ignored in this case

Thanks,

joe

On 10/24/2015 07:42 AM, Chris Fields wrote:
>
> @JoeCarlson <https://github.com/JoeCarlson> unfortunately issues like 
> this are harder to debug w/o a test case. Can you attach a text file 
> (extension |.txt|), using the 'Attach files' option (will be under the 
> text box when you reply)? Alternatively, if you have a bug fix we 
> gladly accept patches or pull requests.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bioperl/bioperl-live/issues/129#issuecomment-150823697>.
>


#!/usr/bin/env perl

# FILE FORMAT: Sam Summary File (SSF) Format 2.1
#
# Column 1:   Sequence accession code e.g. gi|159385
# Column 2:   HMM model name (not taken from stat or align file; set externally by user)
# Column 3:   Total sequence length
# Column 4:   Total HMM Length
# Column 5:   Length of alignment (upper case letters AND gaps that appear within segments)
# Column 6:   Number of matched residues (upper case letters)
# Column 7:   First residue in sequence to match model (first upper case letter)
# Column 8:   Last residue in sequence to match model (last upper case letter)
# Column 9:   First matched position in model
# Column 10:  Last matched position in model
# Column 11:  Evalue
# Column 12:  Simple score
# Column 13:  Reverse score
# Column 14:  Number of matched sequence segments (2+: discontinuous match)
# Column 15:  Colon-separated segment boundaries e.g. 1:51:99:163
#

use Bio::SearchIO;
my $in = Bio::SearchIO->new(-format => 'hmmer',
                            -file   => '/dev/stdin');
while( my $result = $in->next_result ) {
  my $seq_name = $result->query_name;
  my $seq_length = $result->query_length;
  while( my $hit = $result->next_hit ) {
    my $hit_name = $hit->name;
    my $hsp_ctr = 0;
    while( my $hsp = $hit->next_hsp ) {
      my $score = $hsp->score;
      my $evalue = $hsp->evalue;
      my $start = $hsp->start;
      my $end = $hsp->end;
      my $match = $hsp->num_identical;
      my $subject_end = $hsp->{HIT_END};
      my $subject_start = $subject_end - $hsp->{HIT_LENGTH} + 1;
      my $hit_string = $hsp->query_string;
      $hit_string =~ s/[a-z-]//g;
      my $hit_string_length = length($hit_string);
      my $hit_length = $hsp->length;
      my $hsp_ctr++;

print join("\t",$seq_name,$hit_name,$seq_length,0,$hit_length,$hit_string_length,$start,$end,$subject_start,$subject_end,$evalue,$score,0.0,$hsp_ctr,$start.':'.$end),"\n";
     }
  }
}

# hmmscan :: search sequence(s) against a profile database
# HMMER 3.1b1 (May 2013); http://hmmer.org/
# Copyright (C) 2013 Howard Hughes Medical Institute.
# Freely distributed under the GNU General Public License (GPLv3).
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# query sequence file:             testseq
# target HMM database:             /global/homes/j/jcarlson/database/pfam/28.0/pfam_a.hmm
# prefer accessions over names:    yes
# show alignments in output:       no
# model-specific thresholding:     GA cutoffs
# number of worker threads:        2
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Query:       273647885  [L=424]
Scores for complete sequence (score includes all domains):
   --- full sequence ---   --- best 1 domain ---    -#dom-
    E-value  score  bias    E-value  score  bias    exp  N  Model      Description
    ------- ------ -----    ------- ------ -----   ---- --  --------   -----------
    1.7e-24   85.2   3.6    2.7e-12   46.1   0.4    2.3  2  PF00013.25  KH domain
    2.1e-21   75.1   2.3    8.1e-10   38.1   0.1    2.4  2  PF13014.2   KH domain
    4.8e-08   32.6   0.6     0.0031   17.1   0.1    2.3  0  PF07650.13  KH domain


Domain annotation for each model:
>> PF00013.25  KH domain
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   40.0   0.2   4.1e-14   2.2e-10       2      55 ..     155     208 ..     154     210 .. 0.84
   2 !   46.1   0.4   4.9e-16   2.7e-12       2      61 ..     247     312 ..     246     313 .. 0.86

>> PF13014.2  KH domain
   #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
 ---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
   1 !   38.1   0.1   1.5e-13   8.1e-10       2      42 ..     164     203 ..     163     204 .. 0.96
   2 !   36.6   0.3   4.7e-13   2.5e-09       1      43 []     255     301 ..     255     301 .. 0.99

>> PF07650.13  KH domain
   [No individual domains that satisfy reporting thresholds (although complete target did)]



Internal pipeline statistics summary:
-------------------------------------
Query sequence(s):                         1  (424 residues searched)
Target model(s):                       16230  (2852355 nodes)
Passed MSV filter:                       374  (0.0230437); expected 324.6 (0.02)
Passed bias filter:                      340  (0.0209489); expected 324.6 (0.02)
Passed Vit filter:                        18  (0.00110906); expected 16.2 (0.001)
Passed Fwd filter:                         5  (0.000308071); expected 0.2 (1e-05)
Initial search space (Z):              16230  [actual number of targets]
Domain search space  (domZ):               3  [number of targets reported over threshold]
# CPU time: 0.38u 0.34s 00:00:00.72 Elapsed: 00:00:07.52
# Mc/sec: 160.82
//
[ok]

**Comment by pcantalupo** [comment]
@JoeCarlson can you create two gists for your input file and script? It is practically impossible to copy and paste them into an editor (especially the script). Thank you

**Comment by cjfields** [comment]
@pcantalupo @JoeCarlson I'll check whether there is a way to allow attachments from others.

**Comment by JoeCarlson** [comment]
I've created 2 gists. One for a sample hmmer3 output and a simple perl filter

https://gist.github.com/JoeCarlson/6ecaa5702624847eff6a
https://gist.github.com/JoeCarlson/4ab3d341b094ff11ee4c

to demonstrate the issue:
perl hmmerToSSF.pl < demo.hmm3
this prints out:
Missed this line:    [No individual domains that satisfy reporting thresholds (although complete target did)]

Missed this line:    [No individual domains that satisfy reporting thresholds (although complete target did)]

Kalax.0094s0013.1.p     PF13499.2       538     0       0       0       323     419     1       66      2.1e-22 67.5    0       1       323:419
Kalax.0094s0013.1.p     PF13202.2       538     0       0       0       398     416     23      22      2.2e-07 18.6    0       1       398:416

It's OK that the lines were not parsed properly. Fixing the parse will properly discard these lines. But for cases such as this, the output really should not go to stdout. stderr would be better.
