### ISSUE TITLE
Bio::SearchIO::infernal hangs on results from newer Infernal versions

### ISSUE THREAD

**Issue by jeffreybarrick** [bioperl/bioperl-live#131]
Parsing Infernal 1.1.1 output through Bio::SearchIO::infernal seems to hang on some kind of infinite loop when attempting to read it in. I've attached a short Infernal output file that can be used to reproduce the error.

I think this is the same issue as reported here:
http://bio.perl.org/pipermail/bioperl-l/2012-August/036710.html

**Comment by pcantalupo** [comment]
Hi Jeffrey,   I don't see the attachment. Can you create a minimal example the recreates the problem? Please create gists of your input, script and expected output.

**Comment by jeffreybarrick** [comment]
This short script reproduces the error.

`#!/usr/bin/perl
use Bio::SearchIO::infernal;
my $searchio = Bio::SearchIO::infernal->new(-file => "<cmsearch_output.txt");
my $result = $searchio->next_result;`

With this example input file.
[cmsearch_output.txt](https://github.com/bioperl/bioperl-live/files/132960/cmsearch_output.txt)

**Comment by pcantalupo** [comment]
Hi Jeffrey,

Infernal 1.1.1 has changed its output which breaks the SearchIO parser. This is from the Infernal [user guide](http://eddylab.org/infernal/Userguide.pdf)
> The formatting of cmsearch output has also changed. It mirrors the output format of the hmmsearch program from HMMER3,

I may dabble with this but don't expect anything soon. Does anybody want to take this on?

**Comment by cjfields** [comment]
@pcantalupo appears to be trying this out on a branch.  Make sure to note any changes; I am planning on trying for a late spring release for the next bioperl version.

**Comment by pcantalupo** [comment]
@cjfields will do

**Comment by pcantalupo** [comment]
@jeffreybarrick  I added infernal 1.1 support on this [branch](https://github.com/bioperl/bioperl-live/tree/issues/131). Can you put it to the test? Thank you

**Comment by jeffreybarrick** [comment]
Works for my other test case. Thanks!

**Comment by cjfields** [comment]
Merged the fix from @pcantalupo , closing.  Thanks!
