### ISSUE TITLE
RPSBLAST parsing error

### ISSUE THREAD

**Issue by alvesjmp** [bioperl/bioperl-live#132]
We have just noticed a parsing error when dealing with RPSBLAST output. Previous versions of BioPerl could parse the same output with no trouble.

We narrowed down the cause of the problem to a single regex in ``Bio/SearchIO/blast.pm``

But I am getting ahead of myself. The problem first: an error is thrown if the alignment contains something like the following:

```
Query  61   VGILADLQGPKIRLGR--------------------------------------------  76
              I  DL GPK+R G
Sbjct  199  CRIAMDLAGPKLRTGPIAPGPRVIKLRPTRDALGRVLTPARLWLTASESPPPSPPPGPVG  258

Query       ------------------------------------------------------------

Sbjct  259  LPVDPEWLARLEPGDELRFTDARGKKRKLTVTEVDDEGVLAEGSQTAYLANGTLLRLGRH  318

Query  77   ---------FTEGPVLLERGDTFTITVEDGA------EGDGHMCGTTYAGLADDVTPGER  121
                       E  + L+ GD   +T +D        +        T          GER
Sbjct  319  DSTRVGGLPPVEQKLRLKVGDRLVLTRDDAPGDPAQGDAPPARISCTLPEAFRAARVGER  378
```

As you can probably see, the second part of that output snippet contains a query line that is exclusively gaps (the dashes), and therefore contains no sequence coordinates, as would be logical in our opinion. Trying to parse BLAST results containing a line like that results in:

```
------------- EXCEPTION: Bio::Root::Exception -------------
MSG: no data for midline Query       ------------------------------------------------------------
STACK: Error::throw
STACK: Bio::Root::Root::throw /usr/local/share/perl5/Bio/Root/Root.pm:368
STACK: Bio::SearchIO::blast::next_result /usr/local/share/perl5/Bio/SearchIO/blast.pm:1805
```

We dug a bit and found that the problem is caused by the following change in ``Bio/SearchIO/blast.pm`` (the file's header contains the following info at the top: ``# $Id: blast.pm 16123 2009-09-17 12:57:27Z cjfields $``), as shown by part of the ``diff`` output comparing this file and an older one (without any such info at the top), from a version of BioPerl that did not throw the error:

```
1869c1790
<                 if (/^((Query|Sbjct):?\s+(\-?\d+)?\s*)(\S+)\s+(\-?\d+)?/) {
---
>                 if (/^((Query|Sbjct):?\s+(\-?\d+)\s*)(\S+)\s+(\-?\d+)/) {
```

As can be seen, the difference between the two versions is the ``?`` quantifier after the pieces of code that match the sequence coordinates, i.e. ``(\-?\d+)``. Without the ``?``, we understand that the match to the coordinates part of the output became obligatory, that is, no match at all without the presence of that part in the line being examined.

Although uncommon, that piece of (RPS)?BLAST output seems to be perfectly legitimate, and it causes BioPerl to die. Thus, we believe this is a bug.

Please let me know if you need further information that would be of help here.

**Comment by pcantalupo** [comment]
Hi,
I think you might be using an old version of BioPerl (maybe 1.6.1?) This bug has been [fixed](https://redmine.open-bio.org/issues/3064). Please upgrade to the latest [release version 1.6.924](https://metacpan.org/release/BioPerl) or if you want the bleeding edge, [bioperl-live](https://github.com/bioperl/bioperl-live). If you still have problems after upgrading, you are welcome to open a new issue.
