### ISSUE TITLE
Current v1.6.x branch build at Travis-CI fails because of Travis

### ISSUE THREAD

**Issue by fjossandon** [bioperl/bioperl-live#134]
I'm not sure how to fix this. The last build for v1.6.x branch on Travis failed specifically on the Perl 5.20 job because the command "sudo apt-get install libdb-dev graphviz libgd2-xpm-dev libxml2-dev 2>&1 | tail -n 4" from ".travis.yml" failed.

To compare, this is the equivalent Perl 5.20 master branch output that ends with success:
```
[0K$ sudo apt-get install libdb-dev graphviz libgd2-xpm-dev libxml2-dev 2>&1 | tail -n 4
Setting up libdb5.1-dev (5.1.25-11build1) ...
Setting up libdb-dev (5.1.4ubuntu1) ...
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
travis_time:end:078dbcfc:start=1450057084685507506,finish=1450057101523671501,duration=16838163995
```
While on the Perl 5.20 v1.6.x branch:
```
[0K$ sudo apt-get install libdb-dev graphviz libgd2-xpm-dev libxml2-dev 2>&1 | tail -n 4
Failed to fetch http://ppa.launchpad.net/ubuntugis/ppa/ubuntu/pool/main/libx/libxml2/libxml2-dev_2.8.0+dfsg1-5ubuntu2.2~precise1_amd64.deb  Unable to connect to ppa.launchpad.net:http:
Failed to fetch http://ppa.launchpad.net/ubuntugis/ppa/ubuntu/pool/main/libx/libxml2/libxml2_2.8.0+dfsg1-5ubuntu2.2~precise1_amd64.deb  Unable to connect to ppa.launchpad.net:http:
Fetched 3,047 kB in 10s (303 kB/s)
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
travis_time:end:01c3a570:start=1450057546701647944,finish=1450057560789409388,duration=14087761444
```

This is causing "t/LocalDB/Taxonomy/sqlite.t" to fail to load "Bio::DB::Taxonomy::sqlite" :(

Cheers,

**Comment by fjossandon** [comment]
Perl 5.20 v1.6.x branch build log:
https://travis-ci.org/bioperl/bioperl-live/jobs/96659158
Perl 5.20 master branch build log:
https://travis-ci.org/bioperl/bioperl-live/jobs/96658863

**Comment by cjfields** [comment]
Yep, looks like this is failing from a failed dependency installation.  We also should see about upgrading to the later travis workflows, will see what needs to be done for that.

**Comment by cjfields** [comment]
:clap:

**Comment by majensen** [comment]
YEAH baby https://travis-ci.org/bioperl/bioperl-live/builds/99467667

**Comment by fjossandon** [comment]
:clap: :+1:
