### ISSUE TITLE
Update Travis-CI scripts

### ISSUE THREAD

**Issue by cjfields** [bioperl/bioperl-live#135]
We need to update the current Travis-CI workflow to use the new containerized infrastructure:

https://docs.travis-ci.com/user/migrating-from-legacy

This will likely require some debugging, might be best done on a branch.  Any takers?  

Related to #134

**Comment by majensen** [comment]
I could take a look --
MAJ

**Comment by majensen** [comment]
Ok, I'm gonna fork it and fool around.

**Comment by majensen** [comment]
Merged PR #136 which passes all tests using travis containers.
