### ISSUE TITLE
Bio::Align::Utilities::aa_to_dna_aln does not fix display_id

### ISSUE THREAD

**Issue by carandraug** [bioperl/bioperl-live#137]
[Bio::Align::Utilities::aa_to_dna_aln](https://github.com/bioperl/bioperl-live/blob/cf78e07ad6e617090c0e21c89de66a83dc0ee46a/Bio/Align/Utilities.pm#L111) converts an alignment from protein to DNA space. To do this, it uses an hash that maps the aligned proteins display_id to a `Bio::PrimarySeq` of the DNA sequence.  However, the returned alignment retains the display_ids of the proteins instead of the DNA sequences.

The only reason I see to do this is that display_id attribute is not required to create a `Bio::PrimarySeq` but the same is true for the seq attribute.

This seems easy to fix but before I do so, I wonder if it's by design. Can someone comment on this? Other attributes could also be transferred from the DNA sequence. I found `desc` and `display_id` to be the most important for me since I then write the alignments back to fasta.

At the moment, I'm working around this via:

    my $mrna_aln = Bio::Align::Utilities::aa_to_dna_aln($aa_aln, \%seqs);
    for my $aln_seq ($mrna_aln->each_seq)
      {
        $mrna_aln->remove_seq($aln_seq);
    
        my $mrna = $seqs{$aln_seq->display_id};
        $aln_seq->display_id($mrna->display_id);
        $aln_seq->desc($mrna->desc);
    
        $mrna_aln->add_seq($aln_seq);
      }

but I reckon this would be a bit more efficient if this changed in bioperl.

**Comment by hyphaltip** [comment]
Seems valid should be fixable on main trunk. At some level I kind of assumed the IDs would be the same between the two sequences anyways so it didn't matter but I can see how this would be a problem.

**Comment by hyphaltip** [comment]
I have committed fix to this now.
