### ISSUE TITLE
SimpleAlign.pm needs file input named a particular way?

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [bioperl/bioperl-live#146]
Admittedly we're using galaxy to run a pipeline that draws on SimpleAlign.pm, but Galaxy is throwing this error:
Argument "2087/1" isn't numeric in numeric comparison (<=>) at /opt/galaxy/.perlbrew/libs/perl-5.18.1@galaxy/lib/perl5/Bio/SimpleAlign.pm line 777, <GEN0> line 132.

The paired input files are:
07-2087_R1.fastq.gz
07-2087_R2.fastq.gz

Is it the file naming scheme that is causing this error?  Issue is that unless files are coming straight from a miseq, they're often renamed.  Could the file naming check done (I believe it is the _alpha_startend {} function) be improved?  Possibly by using a regular expression (multiline and ignore caps flags set) like the following to identify first and second pair file names if the strings were sorted in \n delimited list?:
^((.+)((1)|(f))(.*))\n((\2)(?(4)2)(?(5)r)(\6))$
This will match both [pref]1[suf] [pref]2[suf] and [pref]f[suf] [pref]r[suf] pairs with one regular expression.

e.g. test data:
a1
a2
a.f
a.r
af.1
af.2
ar
ar1
ar2

af1
dfsdf
ar1

a_1f2
a_1R2

a1f
a1r

Regards,
Damion

**Comment by cjfields** [comment]
@Public-Health-Bioinformatics you can certainly try doing this; would you be interested in trying this on a branch and we can do a pull request?  Main reason I ask, this probably needs to be tested prior to merging (and it makes sense for you to try tweaking the code on your end to get what you want, while possibly testing the changes).

**Comment by Public-Health-Bioinformatics** [comment]
Ok, I'll have a peek at a fix.  I'm a novice perl programmer however.  I'll look at it this week; happy to test within our galaxy pipeline context.

D.

**Comment by Public-Health-Bioinformatics** [comment]
So it looks like the little _alpha_startend {} function at line 777 of SimpleAlign.pm is actually just accomplishing a natural sort of $a and $b inputs :

sub _alpha_startend {
    my ($aname,$astart,$bname,$bstart);
    ($aname,$astart) = split (/-/,$a);
    ($bname,$bstart) = split (/-/,$b);

    if( $aname eq $bname ) {
	return $astart <=> $bstart;
    }
    else {
	return $aname cmp $bname;
    }
}

So I believe this can be simplified to:

Use Sort::Naturally;
…
sub _alpha_startend {
    return ncmp($a,$b)
}

But are there any issues with bioperl importing Sort::Naturally ?  I don't know what that means in terms of dependencies/older perl versions...

**Comment by Public-Health-Bioinformatics** [comment]
It looks like _alpha_startend is designed simply to ensure for two (and only two) file names that are (probably?!) identical in length, to sort one to the first result if it is lesser numerically (after hyphen) or alphabetically (before hyphen).  I believe the identical result can be obtained without relying on Sort::Naturally via a fairly simple:

    sub _alpha_startend {

        if (length($a) < length($b)) {return -1};
        if (length($a) > length($b)) {return 1};

        return ($a cmp $b);
}

**Comment by Public-Health-Bioinformatics** [comment]
FYI, a test program:

```
use strict;
use warnings;
use 5.010;
use Data::Dumper qw(Dumper);

sub _alpha_startend {

    if (length($a) < length($b)) {return -1};
    if (length($a) > length($b)) {return 1};

    return ($a cmp $b);

}

my @words = qw(07-2087_R2.fastq.gz 07-2087_R1.fastq.gz a1
a2 a.f a.r
af.1 af.2
ar
ar1 ar2

af1 dfsdf ar1

a_1f2 a_1R2
a1f a1r);
my @sorted_words = sort(_alpha_startend @words);

say Dumper \@sorted_words;
```

**Comment by cjfields** [comment]
Hi @Public-Health-Bioinformatics .  Having a look at this I don't think it's the file name that is causing the problem, but the alignment being read in and the sequence format used.  Names are in this format: `143E_HUMAN/4-239`.  

The name is being sorted alphanumerically if the sequence name and start coordinate are different, but if they are the same then the names are sorted by last coordinate position (see the `split` call in that function).  For some reason, the `2087/1` is sneaking in there likely from the split, my guess is it's from the sequence header, e.g. there is an extra hyphen in place.  Have any examples of what the seq names look like?

**Comment by cjfields** [comment]
No reply, closing out.  @Public-Health-Bioinformatics please reopen if this is still an issue.
