### ISSUE TITLE
Cannot download/find BPbl2seq module

### ISSUE THREAD

**Issue by JernejTri** [bioperl/bioperl-live#152]
I am trying to use [OAF](http://recode.ucc.ie/oaf/) - a Perl-based tool to analyze cDNA data - with a goal to detect antizyme or antizyme-like sequences. The publication describing the tool is [available here](http://www.ncbi.nlm.nih.gov/pubmed/18384676). I installed Perl (v5.22.2) and BioPerl (v1.6.924) which I believe came with HMMER. I haven't installed FASTA and BLAST locally yet - they are both optional ([see this link](http://recode.ucc.ie/oaf/download)). What I tried to do next is replicate the "my_sequence" example listed on [this website](http://recode.ucc.ie/oaf/download) using the attached .pl script and .fasta file, but ended up stuck with the error stating I am missing a necessary BioPerl module - **BPbl2seq** - which I couldn't download from CPAN. I tried to locate it manually online, but it looks like it doesn't exist anymore. I talked to some Perl specialists who suggested I should reinstall Perl and BioPerl versions that were present around the time this software was developed (2007/2008) with a rationale that they will carry all the necessary modules including BPbl2seq. 

I'd greatly appreciate if you could provide me with some tips on how to proceed. I am working on a Lenovo Yoga PC, 64-bit Windows 8.1.

Thank you!

[OAF.zip](https://github.com/bioperl/bioperl-live/files/282499/OAF.zip)

**Comment by cjfields** [comment]
Hi @JernejTri the last release to have the BPLite-based BLAST report parsing was v1.5.2;
