### ISSUE TITLE
Piped commands not correctly recognised by Bio::SeqIO->new -file option

### ISSUE THREAD

**Issue by RoyChaudhuri** [bioperl/bioperl-live#153]
When a -file option with a leading pipe character is supplied to SeqIO->new, the SeqIO object incorrectly attempts to read rather than write. This seems to be due to a bug in the Bio::Root::IO::cleanfile regex, which does not recognise a leading pipe character.

See mailing list discussion:
http://mailman.open-bio.org/pipermail/bioperl-l/2016-May/089175.html

**Comment by cjfields** [comment]
May push this off until after release

**Comment by cjfields** [comment]
Won't fix this.  The `-file` option is explicitly used for files, not file handles (which is `-fh`).  We would expect a pipe to be added as a file handle, so using `-file` is wrong.

The error that occurs:

```
[cjfields@Chriss-MacBook-Air 153]$ perl test.pl

------------- EXCEPTION: Bio::Root::Exception -------------
MSG: Could not read file '| /Users/cjfields/bin/bgzip -c >  foo.fa.gz': No such file or directory
STACK: Error::throw
STACK: Bio::Root::Root::throw /Users/cjfields/bioperl/bioperl-live/Bio/Root/Root.pm:447
STACK: Bio::Root::IO::_initialize_io /Users/cjfields/bioperl/bioperl-live/Bio/Root/IO.pm:265
STACK: Bio::SeqIO::_initialize /Users/cjfields/bioperl/bioperl-live/Bio/SeqIO.pm:499
STACK: Bio::SeqIO::fasta::_initialize /Users/cjfields/bioperl/bioperl-live/Bio/SeqIO/fasta.pm:87
STACK: Bio::SeqIO::new /Users/cjfields/bioperl/bioperl-live/Bio/SeqIO.pm:375
STACK: Bio::SeqIO::new /Users/cjfields/bioperl/bioperl-live/Bio/SeqIO.pm:421
STACK: Bio::SeqIO::newFh /Users/cjfields/bioperl/bioperl-live/Bio/SeqIO.pm:443
STACK: test.pl:18
-----------------------------------------------------------
```

Is actually correct, it can't find a file literally named `'| /Users/cjfields/bin/bgzip -c >  foo.fa.gz'`

**Comment by RoyChaudhuri** [comment]
Hi Chris,

I agree that it would be better to deal with this using the -fh option. The problem is that currently the SeqIO docs specifically state that -file can handle a piped command. I've updated the docs and will put in a pull request.

Cheers,
Roy.
