### ISSUE TITLE
largefasta.pm not printing last nucleotide

### ISSUE THREAD

**Issue by stuartrbaker** [bioperl/bioperl-live#154]
If a largefasta is printed with write_seq and there is only one nucleotide/amino acid/letter on the final line, the last line is not printed.

line 166 of largefasta.pm reads: while( $start < $end ) {
it should say:  while( $start <= $end ) {
This fixes the problem.

**Comment by cjfields** [comment]
@stuartrbaker thanks for pointing this out, fixed in master
