### ISSUE TITLE
can node labels be parsed as support values for tree rooting purposes?

### ISSUE THREAD

**Issue by jhcepas** [bioperl/bioperl-live#157]
Hi there, 
I have recently expanded the analysis by Czech and Stamatakis regarding [branch support mapping after tree rooting](http://biorxiv.org/content/early/2015/12/25/035360) in tree viewers, and found that some phyloinformatics toolkits might also miss an option to interpret node labels as branch support values. This is problematic when using toolkits to reroot trees produced by common software such as raxml, phyml, fasttree, iqtree, etc... 

@lczech, @stamatak and I are now working on reporting/confirming this in different toolkits. Current tests are here: 
https://github.com/jhcepas/test_branch_support_after_tree_rerooting

does BioPerl have an option to parse node labels as branch supports, so they are correctly remapped to relevant branches after tree rooting?
thanks!

**Comment by cjfields** [comment]
@jhcepas I'll need to check but I would be surprised if it's not possible to at least store this in the Tree.  It may be dependent on the format being parsed however.

**Comment by hyphaltip** [comment]
Nhx should provide this support for where labels go and differentiate node
vs branch. We store what is in the newick format where the nodes hold the
bootstrap.

**Comment by jhcepas** [comment]
thanks @hyphaltip and @cjfields 
is there any example out there to see how trees should be loaded and rerooted to maintain the original placement of branch support values? we would like to include it in our test page.
thanks!

**Comment by jhcepas** [comment]
for the records, using the option  `-internal_node_id` when loading trees did the trick. Re-rooting works well when used. We updated our [test page](https://github.com/jhcepas/test_branch_support_after_tree_rerooting/blob/master/README.md#test_bioperlsh) Thanks!
