### ISSUE TITLE
Review v1.6.x and master branch differences

### ISSUE THREAD

**Issue by cjfields** [bioperl/bioperl-live#161]
We need to review whether commits have been made only to the `v1.6.x` branch that haven't been made to `master`. Branch comparison may be deceptive, as there are very likely dual commits between branches (eg. individual commits w/o merges or rebasing).

**Comment by cjfields** [comment]
See #110 for an example

**Comment by fjossandon** [comment]
@cjfields I made the last commit to the v1.6.x branch back in December, I left the branch updated to the same point than master using cherry-pick commits (except for removed modules that were no longer in master but present in the branch). Below is the branch diff "v1.6.x vs master" at that time:
```
M	.travis.yml
A	Bio/Coordinate/Chain.pm
A	Bio/Coordinate/Collection.pm
A	Bio/Coordinate/ExtrapolatingPair.pm
A	Bio/Coordinate/GeneMapper.pm
A	Bio/Coordinate/Graph.pm
A	Bio/Coordinate/MapperI.pm
A	Bio/Coordinate/Pair.pm
A	Bio/Coordinate/Result.pm
A	Bio/Coordinate/Result/Gap.pm
A	Bio/Coordinate/Result/Match.pm
A	Bio/Coordinate/ResultI.pm
A	Bio/Coordinate/Utils.pm
A	Bio/SearchIO/Writer/BSMLResultWriter.pm
A	Bio/SearchIO/XML/BlastHandler.pm
A	Bio/SearchIO/XML/PsiBlastHandler.pm
A	Bio/SearchIO/blastxml.pm
A	Bio/Tools/Run/StandAloneBlast.pm
A	Bio/Tools/Run/StandAloneNCBIBlast.pm
A	Bio/Tools/Run/StandAloneWUBlast.pm
A	Bio/Tools/Run/WrapperBase.pm
A	Bio/Tools/Run/WrapperBase/CommandExts.pm
M	README.md
A	scripts/utilities/bp_search2BSML.pl
A	t/Coordinate/CoordinateBoundaryTest.t
A	t/Coordinate/CoordinateGraph.t
A	t/Coordinate/CoordinateMapper.t
A	t/Coordinate/GeneCoordinateMapper.t
A	t/SearchIO/blastxml.t
A	t/Tools/Run/Dummy.pm
A	t/Tools/Run/Dummy/Config.pm
A	t/Tools/Run/StandAloneBlast.t
A	t/Tools/Run/WBCommandExts.t
A	t/Tools/Run/WrapperBase.t
A	t/data/ecoli_domains.rps.xml
A	t/data/mus.bls.xml
A	t/data/newblast.xml
A	t/data/plague_yeast.bls.xml
A	t/data/psiblast.xml
```
Only `.travis.yml` and `README.md` were different. Since no commits has been made since then to the branch, its safe to assume that there are no commits in v1.6.x that are not in master.

I have some time now, so if you want I can update v1.6.x branch to include the last commits made to master.

**Comment by cjfields** [comment]
@fjossandon no need, v1.6.x will be a dead branch as we're working on a 1.7 off master now.  I mainly want to ensure that commits don't get lost on the v1.6.x branch, but if everything is in master then there isn't a problem.  We've generally been pretty good about carrying them over.

**Comment by fjossandon** [comment]
As you can see by the diff, in December they were almost equal, the travis file and README differences were branch-specific text. There were no more commits since I synched them, so you can rest assured that there is no commit lost in v1.6.x ;)
You can close this issue.

**Comment by cjfields** [comment]
Thanks @fjossandon that's awesome, glad you were on top of it 👍 !
