### ISSUE TITLE
Review INSTALL, INSTALL.WIN docs

### ISSUE THREAD

**Issue by cjfields** [bioperl/bioperl-live#165]
Make sure that links and other bits are updated to reflect new site, etc.

**Comment by cmdcolin** [comment]
Is there any reason why the install docs are so complicated?

Why is it not as simple as "cpan BioPerl" or "cpanm BioPerl" (maybe suggest --notest too)? I imagine that some older systems could have problems but I think at least suggesting the "easy way" is useful

Cpanm can install from github pretty easily too, e.g. "cpanm git://github.com/bioperl/bioperl-live.git" (or specific branch "cpanm --notest git://github.com/bioperl/bioperl-live.git@v1.6.x")

Cpanm will install those BioPerl scripts by default too, so I guess the section on installing the scripts seems unnecessary to me as well?

Just curious, cause I remember in the past as a newer I was quite confused by BioPerl setup instructions, but if a simpler command can suffice, i'd recommend it!

**Comment by cjfields** [comment]
Moved to markdown files

**Comment by cjfields** [comment]
@cmdcolin These were pre-cpanm and really need to be modernized.  The main reason it's on the docket for updates!

**Comment by cjfields** [comment]
Mainly updated.  We need a better way to keep these in sync with docs on the main page but for now this works.

**Comment by cmdcolin** [comment]
Currently the Docker method and the "hard way" are suggested before the "easy" way in the install.md. Is it worth just putting the easy way up front?

**Comment by cmdcolin** [comment]
Actually I just misread "Preliminary Preparation" as a hard way. But considering most newer platforms have up to date perls, maybe the preliminary preparation is not necessary?

Just thinking in the interest of a new user :)
