### ISSUE TITLE
MeSH results change depending on the web module used

### ISSUE THREAD

**Issue by fjossandon** [bioperl/bioperl-live#171]
I have 2 test systems, my Windows system comes with `WWW::Mechanize` installed, and my Ubuntu systems don't have it so it uses `Bio::WebAgent`. The amazing thing is that one of the MeSH tests (https://github.com/bioperl/bioperl-live/blob/master/t/RemoteDB/MeSH.t#L25-L27) pass if the webagent is `Bio::WebAgent` (returns 2 twigs), but fails if the webagent is `WWW::Mechanize` (returns 3 twigs). I confirmed this by forcing MeSH to use WebAgent and then it returns the expected 2 twigs.

Why the result difference? I looked at the webpages that both returns and they have different versions:
Mechanize: `<a href="/mesh/2016/mesh_browser/MBrowser.html">`
WebAgent: `<a href="/mesh/2003/MBrowser.html">`

For the resulting trees, Mechanize retrieves these twigs:
* Fats [D10.212] -> Dietary Fats [D10.212.302]
* Food [G07.203.300] -> Dietary Fats [G07.203.300.375]
* Food [J02.500] -> Dietary Fats [J02.500.375]

And WebAgent retrieves these twigs:
* Fats [D10.516.212] -> Dietary Fats [D10.516.212.302]
* Food [J02.500] -> Dietary Fats [J02.500.375]

It looks like `Bio::WebAgent` retrieves an older version of the webpage (and maybe older version of results?). I'm not clear on why they don't retrieve the same webpage version.

Here I made a Gist to store the different HTM pages that were retrieved (main page and trees), in case somebody want to check them:
https://gist.github.com/fjossandon/6c434deccdbe2a1a7876e4bb57f6d448

**Comment by heikkil** [comment]
The NIH MeSH browser is updated weekly and the URL for each passing year is kept alive.
The default URL in Bio/DB/MeSH.pm for the web page is https://www.nlm.nih.gov/mesh/MBrowser.html and is used by `WWW::Mechanize`. When that module is not available, ti falls back to `Bio::WebAgent` (or `Bio::Root::HTTPget`). In latter cases the URL contains a hard coded year value which have not been updated since the module was written, e.g.:

     http://www.nlm.nih.gov/cgi/mesh/2003/MB_cgi?field=entry&term=food 

A quick fix would be to update the year string. Even better would be to read the current year from system and use that, but the script might fail at new year. :)

**Comment by cjfields** [comment]
@heikkil we can probably deal with the intermittent fail 😄 

I'll be working on CPAN Testers fails today to shore those up, then will circle back around to these.  If anyone wants to take this on I would be more than grateful ( 🍻 ), you can assign yourself to the ticket

**Comment by fjossandon** [comment]
@heikkil 
> The default URL in Bio/DB/MeSH.pm for the web page is https://www.nlm.nih.gov/mesh/MBrowser.html and is used by `WWW::Mechanize`.

Why `Bio::WebAgent` does not use the same page? It cannot work with it?

> A quick fix would be to update the year string. Even better would be to read the current year from system and use that, but the script might fail at new year.

Maybe not fail, at init, when `Bio::WebAgent` sets the webpage it will use (https://github.com/bioperl/bioperl-live/blob/master/Bio/DB/MeSH.pm#L182-L186), it could check if it can connect to `http://www.nlm.nih.gov/cgi/mesh/CURRENT_YEAR/MB_cgi`, and if it fails (because the new page is  not yet online) fall back to `http://www.nlm.nih.gov/cgi/mesh/PREVIOUS_YEAR/MB_cgi`... Maybe something like:
```
my $pass = 0;
my $year = CURRENT_YEAR;
while ($pass == 0 or $year > 2003): {
    connect to $year page;
    if (connection successful) {
        $pass = 1;
    }
    else {
        $year -= 1
    }
}
set webpage using $year, with $year == 2003 if every connection fails (so the while() does not get trapped in endless loop);
```
:wink:

**Comment by heikkil** [comment]
@fjossandon, it might have been the the path of least resistance. 

There is no magic in year 2003. There might be many more earlier scripts in the server. 
Go ahead and implement safeguards you suggest for a New Year transit if  you think they are needed. However, I doubt it will be necessary to go beyond the previous year.

Hint: localtime() is a funny function. This syntax works:

    my $year = ${[localtime()]}[5]+1900;

**Comment by cjfields** [comment]
I agree w/ @heikkil , the first implementation doesn't need to be so fine-grained that it deals with week w/ New Years, as long as it addresses the majority of cases.  But it should be easy enough to deal with this using `yday` and fall back to the prior year if  < 7 or so.

**Comment by fjossandon** [comment]
I finished working on MeSH and the code is in PR #177 .
Now both `WWW::Mechanize` and `Bio::WebAgent` provide the same result. But there is 1 problem which goes beyond my knowledge on how to fix it.

If I force MeSH to ignore the other 2 and use `Bio::Root::HTTPget`, it cannot get results because the webpage it retrieves is very different from the other 2 (even after fixing this year version issue). I put this new page I got as "Bio-Root-HTTPget_page.htm" in the Gist https://gist.github.com/fjossandon/6c434deccdbe2a1a7876e4bb57f6d448

@heikkil could you check  `Bio::Root::HTTPget` results?? That or removed its use on MeSH if it can be fixed.

**Comment by heikkil** [comment]
I can not understand what `Bio::Root::HTTPget` is doing now. Too many things have changed over the years.

I'll accept the PR and remove `Bio::Root::HTTPget` calls.

Note for future: Tests do not cover all options

**Comment by cjfields** [comment]
It may be worth looking into how often `Bio::Root::HTTPget` is used in the core.  It's possible there is some bit rot hidden by the use of other options that work.

**Comment by fjossandon** [comment]
@cjfields Cannot look it myself for now, but currently `Bio::Root::HTTPget` is only called by `Bio::DB::Expression` (https://github.com/bioperl/bioperl-live/blob/master/Bio/DB/Expression.pm#L85) and `Bio::DB::Registry` (https://github.com/bioperl/bioperl-live/blob/master/Bio/DB/Registry.pm#L78), and t/Root/HTTPget.t of course.
