### ISSUE TITLE
bioperl DIST website is down

### ISSUE THREAD

**Issue by bcosc** [bioperl/bioperl-live#178]
http://bioperl.org/DIST is giving a 404.

Specifically I want this file:

$wget http://bioperl.org/DIST/BioPerl-1.6.1.tar.gz
--2016-07-11 20:34:36--  http://bioperl.org/DIST/BioPerl-1.6.1.tar.gz
Resolving bioperl.org (bioperl.org)... 192.30.252.153, 192.30.252.154
Connecting to bioperl.org (bioperl.org)|192.30.252.153|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-07-11 20:34:36 ERROR 404: Not Found.

**Comment by bosborne** [comment]
Bryan,

You can find 1.6.1 here:

https://github.com/bioperl/bioperl-live/releases/tag/bioperl-release-1-6-1 <https://github.com/bioperl/bioperl-live/releases/tag/bioperl-release-1-6-1>

But what documentation told you to download that from bioperl.org <http://bioperl.org/>? If there’s documentation saying that we need to change it.

Brian O.

**Comment by cjfields** [comment]
@bcosc We're very unlikely to reopen the DIST site as it was hosted on a separate cloud server.  Let us know if this is due to out-of-date documentation on our site or if it originates from another location.

**Comment by cjfields** [comment]
@bosborne know of any way we can redirect http://bioperl.orf/DIST to point to the Github releases URL?

**Comment by bcosc** [comment]
@bosborne I was downloading VEP at Ensembl and their install script directs to that link. Specifically I was downloading version 78, its now version 85 so I'm not sure how likely it is that people will run into this.

**Comment by bosborne** [comment]
This one is closed, the bad link is at ensembl.org. Tried to use the "Contact" link over there to notify them, that was also a bad link, not much else we can do.
