### ISSUE TITLE
BioPerl Build

### ISSUE THREAD

**Issue by quinnol** [bioperl/bioperl-live#189]
Hi 
I am trying to install Bio perl to use Virusfinder 2, but have had alot of issues, the fisrt being the following packages as part of Bioperl would not install or work, im not sure why?

Bio::DB::Sam                    Failed
Bio::DB::Sam::Constants   Failed
Bio::SeqIO                        Failed
Bio::SearchIO                    Failed
Config::General                Failed

This package requires Module::Build v0.42 or greater to install itself.
Base class package "Module::Build" is empty.
    (Perhaps you need to 'use' the module which defines that package first,
    or make that module available in @INC (@INC contains: /srv/global/scratch/groups/sbs/BioPerl . /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5).
 at (eval 3) line 1
BEGIN failed--compilation aborted at (eval 3) line 1.
BEGIN failed--compilation aborted at Bio/Root/Build.pm line 39.
Compilation failed in require at Build.PL line 14.
BEGIN failed--compilation aborted at Build.PL line 14.
-bash-4.1$ :install Build v0.42

I get this message, and have tried to find build v0.42 or greater, but to no avail! Do you know what the error is? I have downloaded the latest master bioperl but it still seems to have the same issue.

Hope someone can help.

Cheers

Ol

**Comment by bosborne** [comment]
quinnol,

Can you tell us how you’re trying to install BioPerl? And show us the commands?

Thank you,

Brian O.

**Comment by quinnol** [comment]
HI Brian


Thanks for your reply. I installed a new Bioperl yesterday, by downloading BioPerl-1.6.924.tar.gz<http://search.cpan.org/CPAN/authors/id/C/CJ/CJFIELDS/BioPerl-1.6.924.tar.gz> from http://search.cpan.org/dist/BioPerl/Bio/SeqIO.pm

Bio::SeqIO - search.cpan.org<http://search.cpan.org/dist/BioPerl/Bio/SeqIO.pm>
search.cpan.org
NAME . Bio::SeqIO - Handler for SeqIO Formats. SYNOPSIS use Bio::SeqIO; $in = Bio::SeqIO->new(-file => "inputfilename" , -format => 'Fasta ...

to use with

https://bioinfo.uth.edu/VirusFinder/


Bioinformatics and Systems Biology Laboratory, Vanderbilt<https://bioinfo.uth.edu/VirusFinder/>
bioinfo.uth.edu
VirusFinder 2 is a new software tool for characterizing intra-host viruses through next generation sequencing (NGS) data. It implements our recently developed ...

I unzipped file  and cd to the Bioperl directory where i used command ./Build install

I am trying to run the following command which requires Bioperl:

perl /srv/global/scratch/groups/sbs/VirusFinder2.0/VirusFinder.pl -c /srv/global/scratch/groups/sbs/VirusFinder2.0/OIliver_virus_config.txt -o /srv/global/scratch/quinnol/RNA_Seq/Virus_Finder

I get this error message

Can't locate Bio/SeqIO.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /srv/global/scratch/groups/sbs/VirusFinder2.0/VirusFinder.pl line 49.
BEGIN failed--compilation aborted at /srv/global/scratch/groups/sbs/VirusFinder2.0/VirusFinder.pl line 49.


When  i run this to check the system:
perl /srv/global/scratch/groups/sbs/VirusFinder2.0/sys_check.pl

It says these packages have failed for some reason.....

Bio::DB::Sam Failed
> Bio::DB::Sam::Constants Failed
> Bio::SeqIO Failed
> Bio::SearchIO Failed
> Config::General Failed
>
I also get this error!

> This package requires Module::Build v0.42 or greater to install itself.
> Base class package "Module::Build" is empty.
> (Perhaps you need to 'use' the module which defines that package first,
> or make that module available in @INC <https://github.com/INC> (@INC <https://github.com/INC> contains: /srv/global/scratch/groups/sbs/BioPerl . /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5).
> at (eval 3) line 1
> BEGIN failed--compilation aborted at (eval 3) line 1.
> BEGIN failed--compilation aborted at Bio/Root/Build.pm line 39.
> Compilation failed in require at Build.PL line 14.
> BEGIN failed--compilation aborted at Build.PL line 14.
> -bash-4.1$ :install Build v0.42
>
Cheers

Oliver




PhD Candidate
School of Biological Sciences
Victoria University of Wellington
P.O. Box 600
Wellington
New Zealand
Phone: 64 22 308 3701
________________________________

**Comment by bosborne** [comment]
quinnol,

What happens when you do this command:

>cpanm CJFIELDS/BioPerl-1.6.924.tar.gz

Brian O.

**Comment by quinnol** [comment]
Hi Brian


Same issues occur, i have out IT guy looking at it now, i'll let you know how he gets on!


Regards


Oliver


PhD Candidate
School of Biological Sciences
Victoria University of Wellington
P.O. Box 600
Wellington
New Zealand
Phone: 64 22 308 3701
________________________________

**Comment by cjfields** [comment]
@quinnol please post the reply to Github when you get a chance.

**Comment by cjfields** [comment]
@quinnol judging by one of your posts it seems that installation either didn't work or you are installing to a location not found by your system perl (or whatever version of perl happens to be in your path).  

Also note, Bio::DB::Sam and Bio::DB::Sam::Constants are not included in the main bioperl distribution, these are separate releases on CPAN.

**Comment by cjfields** [comment]
I missed this part:

> This package requires Module::Build v0.42 or greater to install itself.

Bioperl requires an updated Module::Build to run; this can be installed by your sysadmin for your version of perl.  Can you try this?

**Comment by cjfields** [comment]
No reply, closing for now.  @quinnol feel free to reopen if this changes

**Comment by elenaduke** [comment]
hey I am having the same issue with as this person. I have the most updated version of Module::Build (v.4224). I am able to install a local library but when i try to run a program that uses bioperl i get this message: 
Can't locate Bio/SeqIO.pm in @inc (@inc contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /srv/global/scratch/groups/sbs/VirusFinder2.0/VirusFinder.pl line 49.
BEGIN failed--compilation aborted at /srv/global/scratch/groups/sbs/VirusFinder2.0/VirusFinder.pl line 49.

As I understand my program is looking for bioperl in the wrong place (not the local library). 
When I try to install Bioperl globally, i get an error message saying that I dont have permission. 

Can you let me know what you think is best? 
Elena

**Comment by hyphaltip** [comment]
your PATH or @inc do not include the local directory where you installed - you will need to update PERL5LIB for example to point to ~/lib/perl5 (or wherever you installed it).
