### ISSUE TITLE
WrapperBase.t test number 19 assumes "test_name" cannot be a valid binary in $PATH

### ISSUE THREAD

**Issue by DanielMedinaStacey** [bioperl/bioperl-live#200]
Installing BioPerl 1.6.924 via CPAN resulted in the following cryptic (in my opinion) failure:

```
#   Failed test 'pretend program name not found as executable'
#   at t/Tools/Run/WrapperBase.t line 87.
# expecting: Regexp ((?^:Cannot find executable))
# found: normal exit
# Looks like you failed 1 test of 27.
```

In the code of WrapperBase.t I found the following starting at line 81:

```
[...]
$obj->program_name('test_name');

# program_path
is $obj->program_path, File::Spec->catfile('test_dir', 'test_name'.($^O =~ /mswin/i ?'.exe':'')), 'program_path was correct';

# executable
throws_ok { $obj->executable } qr/Cannot find executable/, 'pretend program name not found as executable';
$obj->program_name('perl');
ok $obj->executable, 'perl found as executable';
[...]
```
In summary, **`test_name`** is passed as a program name to the WrapperBase object under the assumption that correct behaviour will be to throw "Cannot find executable". However, in my distribution I happened to have `libirman` installed, which provides the executable **`test_name`**.  This resulted in a mistaken test failure and much confusion until I discovered the reason. Temporarily uninstalling `libirman` solved the issue, but I could have easily be stumped and given up.

My suggestions would be to:

1. Change the pretend program name to one less likely to conflict with other software (e.g. **`test_this_binary_is_imaginary`**)
2. Just in case, report the name of the pretend program in case of failure for the benefit of the user.

Thanks.

**Comment by cjfields** [comment]
Hi @DanielMedinaStacey this is fixed in https://github.com/bioperl/bioperl-run/commit/8fb4d9f9fe8c1e5af3a9f7f959fcc9b1143e030d .  Thanks for the report!
