### ISSUE TITLE
Bio::SeqIO::embl does not print out custom ID line

### ISSUE THREAD

**Issue by RoyChaudhuri** [bioperl/bioperl-live#201]
If a custom _id_generation_func is used, the ID line is not printed out, unlike the behaviour with a custom _ac_generation_func.

Current behaviour:
perl -MBio::SeqIO -MBio::Seq -e 'my $out=Bio::SeqIO->new(-format=>qw(embl)); my $seq=Bio::Seq->new(-seq=>"ACTG", -accession_number=>"TESTAC", -id=>"TESTID"); $out->_id_generation_func(sub{"Custom_".$_[0]->id}); $out->write_seq($seq)'
AC   TESTAC;
XX
XX
FH   Key             Location/Qualifiers
FH
XX
SQ   Sequence 4 BP; 1 A; 1 C; 1 G; 1 T; 0 other;
     actg                                                                      4
//

Expected:
perl -MBio::SeqIO -MBio::Seq -e 'my $out=Bio::SeqIO->new(-format=>qw(embl)); my $seq=Bio::Seq->new(-seq=>"ACTG", -accession_number=>"TESTAC", -id=>"TESTID"); $out->_id_generation_func(sub{"Custom_".$_[0]->id}); $out->write_seq($seq)'
ID   Custom_TESTID
XX
AC   TESTAC;
XX
XX
FH   Key             Location/Qualifiers
FH
XX
SQ   Sequence 4 BP; 1 A; 1 C; 1 G; 1 T; 0 other;
     actg                                                                      4
//

**Comment by cjfields** [comment]
Hi @RoyChaudhuri can you make a pull request?  This will trigger running tests from the fork on Travis.

**Comment by cjfields** [comment]
@RoyChaudhuri nevermind, you already did that (I had a cached page).  I'll pull that in, thanks!
