### ISSUE TITLE
inconsistent info in DEPENDENCIES

### ISSUE THREAD

**Issue by martin-mann** [bioperl/bioperl-live#207]
the file states

```
The DBD::mysql, DB_File and XML::Parser modules require other applications or
databases: MySQL, Berkeley DB, and expat respectively.
```

but `DBD::mysql` and `DB_File` are not listed anywhere else in the file. 

What is correct?

**Comment by bosborne** [comment]
Martin,

The key line is below that line:

The DBD::mysql, DB_File and XML::Parser modules require other applications or
databases: MySQL, Berkeley DB, and expat respectively.

NB: This list of packages is not authoritative. See the 'requires',
'build_requires' and 'recommends' sections of Build.PL instead.

Brian O.

**Comment by martin-mann** [comment]
Hi Brian,

thanks for the answer. Meanwhile I found it in Build.PL. Here, the first two packages are listed in the `requires` field of the `auto_features`. 

The point was, I was installing bioperl with "all features on" and only checked the `DEPENDENCIES` file. Thus, the autofeature deps were missing during build.

Thanks for the feedback,
Martin
