### ISSUE TITLE
Inline C in eval breaking Inline for other modules

### ISSUE THREAD

**Issue by carsonhh** [bioperl/bioperl-live#215]
After updating BioPerl via CPAN, I started to have a large number of modules fail that use Inline::C internally. After a lot of investigating I discovered that these other modules would fail whenever Bio::DB::Fasta was loaded before them. The issue appears to be in Bio::DB::IndexedBase. Inline::C has been added in an eval statement, and somehow this statement is causing Inline::C to enter a weird state and killing it for other modules (they either drop methods or drop the the shared object version after loading, both of which result in runtime failures).

This is the code snippet causing the issue in perl 5.16.3 -->

```
# C can do perfrom _strip_crnl much faster. But this requires the
# Inline::C module which we don't require people to have. So we make
# this optional by wrapping the C code in an eval. If the eval works,
# the Perl strip_crnl() function is overwritten.
eval q{
    use Inline C  => <<'END_OF_C_CODE';
    /* Strip all new line (\n) and carriage return (\r) characters
       from string str
    */
    char* _strip_crnl(char* str) {
        char *s;
        char *s2 = str;
        for (s = str; *s; *s++) {
            if (*s != '\n' && *s != '\r') {
              *s2++ = *s;
            }
        }
        *s2 = '\0';
        return str;
    }
END_OF_C_CODE
};
```

**Comment by carsonhh** [comment]
I've attached a patch file that fixes the issue (patched against current BioPerl-live to make it easier to apply).

Basically to get runtime replacement of the function in the presence of Inline::C, I have it use the Inline->bind() function rather than an eval statement. This is immediately preceded by a call to eval 'require Inline::C' which allows us to do the test if($INC{'Inline/C.pm'}). I also wrapped the replacement inside the function, so the replacement occurs the first time the function is called. If it can't find Inline:C, then it replaces it with a perl based function.

These changes avoid breaking Inline::C in weird ways by doing 'use' inside of an eval statement. Also it ensures that the function replacement occurs at runtime and not compile time. This will avoid issues with other Inline based modules that may 'use' or 'require' the Bio::DB::IndexedBase module before linking their own Inline::C code.


[IndexedBase.patch.gz](https://github.com/bioperl/bioperl-live/files/845173/IndexedBase.patch.gz)

**Comment by carsonhh** [comment]
Also one more optimization you may want to add (not currently in the patch).  

This function is very slow. On a 1GB test string, it 400MB string, it takes 17-18 seconds -->

```
my $str = shift;
$str =~ s/$nl//g;
$str =~ s/$cr//g;
return $str;
```


However this function is fast and still written in Perl (takes **0.8 seconds** on same string) -->

```
my $str = shift;
$str =~ tr/\n\r//d; #translate with delete
return $str;
```

If you use that code snippet instead, then you eliminate the need for the Inline::C code in the first place. You can also make it operate on the string reference to make it even faster (avoid string copying in the string and on the return value)

```
my $str_ref = shift;
$$str_ref =~ tr/\n\r//d; #translate with delete
```

**Comment by bosborne** [comment]
Patch applied, and replaced "s" with "tr" in _strip_crnl().
