### ISSUE TITLE
Please provide the location of the Apache directory

### ISSUE THREAD

**Issue by ojonuba** [bioperl/bioperl-live#217]
I am trying to install bioperl. It tells me to provide this:

Please provide the location of the Apache directory.

I can't find it.

**Comment by bosborne** [comment]
This doesn’t sound right, it sounds more like a mod_perl installation, or a GBrowse installation.

Can you tell us _how_ you are trying to install Bioperl?

**Comment by cjfields** [comment]
@ojonuba BioPerl doesn't require an Apache installation, but GBrowse (and other web-based tools) that also require BioPerl also require Apache (as @bosborne mentioned).

I'm closing this ticket out, but feel free to reopen if you find this to be a BioPerl-specific problem.
