### ISSUE TITLE
Bio::SeqIO Ignores first line of sequence

### ISSUE THREAD

**Issue by VAR121** [bioperl/bioperl-live#227]
perl version : 5.18.2
bioperl version: 1.007001
Issue: SeqIO ignores first line of Input(despite having empty description line.
-----------------Input-------------------------
>P1;653279462_Curvibactergracilis

----MGMNIGSGSGS-SEPEVMMDINTTPL
IDVMLVLLIMLIITIPAQLHSVNLDMPVSA
PP--TKKVD-PVVVHIDIDKQSVIHWNGAA
LASRAELEAHLGEAVRLQP-----------
----QPEIHIRSDAKAKYEAVAAVMANAQR
VGLTKLGIVGSEQFVN-
*
-----------------Input-------------------------
-----------------program-------------------------
use strict;
use Bio::SeqIO;

my $file  = $ARGV[0];
my $seqio = Bio::SeqIO->new(
    -file   => $file,
    -format => 'pir'
);

while ( my $seq = $seqio->next_seq() ) {
    print $seq->seq, "\n";
}
-----------------program-------------------------

-----------------output-------------------------#as a single string no new-lines
IDVMLVLLIMLIITIPAQLHSVNLDMPVSSPP--TKKID-PVVIKIDVDANSVINWNGRPLAGRADLELKLTEAAATQP---------------QPELHIRSHAKAKYESVALVMASAQRIGLTKLGIVGSEQFVN-
-----------------output-------------------------#as a single string no new-lines

**Comment by bosborne** [comment]
Fixed in pir-no-desc-line branch
