### ISSUE TITLE
Bio::AlignIO phylip to fasta conversion crash

### ISSUE THREAD

**Issue by pgajer** [bioperl/bioperl-live#229]
use strict;
use warnings;
use diagnostics;
use Bio::AlignIO;
use Bio::SimpleAlign;

my $inFile = "test.phy";
my $outFile = "test.fa";

my $in  = Bio::AlignIO->new(-file   => $inFile,
			    -format => 'phylip',
			    -interleaved => $interleaved,
			    -idlength => 30);

my $out = Bio::AlignIO->new(-file   => ">$outFile",
			    -format => 'fasta');

while ( my $aln = $in->next_aln() )
{
  $out->write_aln($aln);
}

Crashes with the error message

Use of uninitialized value $name in substitution (s///) at
	/usr/local/lib/perl5/site_perl/5.20.0/Bio/AlignIO/phylip.pm line 222, <GEN0> line 10 (#1)

on the attached file
[test.phy.gz](https://github.com/bioperl/bioperl-live/files/1042144/test.phy.gz)

**Comment by bosborne** [comment]
Pawel,

This should work:

my $in = Bio::AlignIO->new(
    -file        => $inFile,
    -format      => 'phylip',
    -interleaved => $interleaved,
    -longid      => 1
);

-longid, rather than -idlength. Looked at the code, it turns out that “-idlength” is for writing, “-longid” is for reading.

The documentation on this does not make this distinction clear, I’ll correct that.

Brian O.

**Comment by bosborne** [comment]
Clarified the documentation.

**Comment by pgajer** [comment]
Thank you very much Brian for taking care of this !
:)
pawel
