### ISSUE TITLE
WebDBSeqI Request Error

### ISSUE THREAD

**Issue by rabi1029** [bioperl/bioperl-live#230]
Hi, 
I got a "HTTP/1.1 400 Bad Request" error when I used get_Seq_by_acc by version 1.007001:

------------- EXCEPTION: Bio::Root::Exception -------------
MSG: WebDBSeqI Request Error:
HTTP/1.1 400 Bad Request
......
ID list is empty! In it there are neither IDs nor accessions.
 Error: CEFetchPApplication::proxy_stream(): HTTP/1.1 400 Bad Request

STACK: Error::throw
STACK: Bio::Root::Root::throw /home/rabi/perl5/lib/perl5/Bio/Root/Root.pm:447
STACK: Bio::DB::WebDBSeqI::_stream_request /home/rabi/perl5/lib/perl5/Bio/DB/WebDBSeqI.pm:779
STACK: Bio::DB::WebDBSeqI::get_seq_stream /home/rabi/perl5/lib/perl5/Bio/DB/WebDBSeqI.pm:472
STACK: Bio::DB::NCBIHelper::get_Stream_by_acc /home/rabi/perl5/lib/perl5/Bio/DB/NCBIHelper.pm:502
STACK: Bio::DB::WebDBSeqI::get_Seq_by_acc /home/rabi/perl5/lib/perl5/Bio/DB/WebDBSeqI.pm:190
STACK: main::get_seq test.pl:12
STACK: test.pl:5
-----------------------------------------------------------

------------- EXCEPTION: Bio::Root::Exception -------------
MSG: acc AIL64431.1 does not exist
STACK: Error::throw
STACK: Bio::Root::Root::throw /home/rabi/perl5/lib/perl5/Bio/Root/Root.pm:447
STACK: Bio::DB::WebDBSeqI::get_Seq_by_acc /home/rabi/perl5/lib/perl5/Bio/DB/WebDBSeqI.pm:199
STACK: main::get_seq test.pl:12
STACK: test.pl:5
-----------------------------------------------------------

My scripts is like:
use Bio::DB::GenBank;

my $seq = &get_seq('AIL64431.1');
print "$seq\n";

sub get_seq{
    my $acc = shift;

    my $gb = Bio::DB::GenBank->new();
    my $seqObj = $gb->get_Seq_by_acc($acc);
    if($seqObj->seq){
        return $seqObj->seq;
    }else{
        return "$acc id can't find";
    }
}

I don't know what I did wrong.

**Comment by bosborne** [comment]
You want to use Bio::DB::GenPept, not Bio::DB::GenBank. That is a protein accession.
