### ISSUE TITLE
Problems downloading and parsing GenBank records

### ISSUE THREAD

**Issue by molleraj** [bioperl/bioperl-live#232]
I have been using a script to parse GenBank files to find taxonomic information corresponding to bacterial genomes. After several tries, my script has failed with the following error:

...
`Bacteria_Actinobacteria_Streptomycetales_Streptomycetaceae_Streptomyces_Streptomyces_sp._4F`
`Bacteria_Actinobacteria_Streptomycetales_Streptomycetaceae_Streptomyces_Streptomyces_glaucescens`
`--------------------- WARNING ---------------------`
`MSG: Unbalanced quote in:`
`/locus_tag="M271_25565"`
`/inference="COORDINATES: ab initio prediction:GeneMarkS+"`
`/note="Derived by automated computational analysis using`
`gene prediction method: GeneMarkS+."`
`/codon_start=1`
`/transl_table=11`
`/product="membrane protein"`
`/protein_id="YP_008791527.1"`
`/db_xref="GeneID:17596261"`
`/translation="MPSPTSLAPAGPTATPTRTTATARRLMAICGTLLAALLCALSVG`
`ANSASAHAALTSTDPADGSVVKTAPREVTLNFSEGVLLSGDSVRVLDPKGKRVDTGKT`
`AHVDGKSSTAAAGLHSGLPDG Error: External viewer error: Empty Response. Bytes read: 0 Status:` `TimeoutNo further qualifiers will be added for this feature`
---------------------------------------------------`

After this, the script seems to halt for hours at least, if not indefinitely...
Is this a BioPerl or GenBank issue? Any help would be appreciated.

**Comment by cjfields** [comment]
Hi @molleraj this appears to have been addressed via our discussion on the mail list.  Closing, but feel free to reopen if you feel this is a bug in Bioperl
