### ISSUE TITLE
failure in build test  - 1.007001

### ISSUE THREAD

**Issue by SilentGene** [bioperl/bioperl-live#239]
Hi,
When I tried to build the latest version of Bioperl-1.007001 in my cluster(Red Hat Enterprise Linux Server release 6.2), an error occurred:
```
Test Summary Report
-------------------
t/PodSyntax.t                        (Wstat: 256 Tests: 927 Failed: 1)
  Failed test:  806
  Non-zero exit status: 1
Files=325, Tests=20523, 151 wallclock secs ( 4.24 usr  1.09 sys + 136.90 cusr 12.28 csys = 154.51 CPU)
Result: FAIL
Failed 1/325 test programs. 1/20523 subtests failed.
```
And I found the log previously:

```
t/PodSyntax.t .......................... 738/927
#   Failed test 'Bio/DB/Taxonomy/sqlite.pm'
#   at /usr/share/perl5/Test/Pod.pm line 219.
# Bio/DB/Taxonomy/sqlite.pm (64): L<text|scheme:...> is invalid according to perlpod
t/PodSyntax.t .......................... 872/927 # Looks like you failed 1 test of 927.
t/PodSyntax.t .......................... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/927 subtests
```
What should I do next?

**Comment by SilentGene** [comment]
I've tried to install a legacy version BioPerl-1.6.924, and it run well. So I guess this is the issue present in the new version.

**Comment by bosborne** [comment]
Heyu,

I can’t reproduce this error, when I check the POD for that module on my computer it looks fine. And it’s not that significant, it just means you won’t have the documentation for that module.

I don’t know how you’re installing but if you’re using cpanm you could do “cpanm —force …”.

Brian O.

**Comment by SilentGene** [comment]
Because of the lack of sudo privilege and Internet connection on my cluster, I install BioPerl with local::lib and the most recent minicpan(add the BioPerl tarball in the source), I don't know if this is the reason leading to the error.

**Comment by cjfields** [comment]
Seems like an easy fix; anyone want to take it on in a fork?

**Comment by cjfields** [comment]
@SilentGene I'm not seeing this specific error either.  The POD in question doesn't even exist in the file mentioned.   You mentioned:

> ...(add the BioPerl tarball in the source)

in your last reply; what did you mean by that?

**Comment by SilentGene** [comment]
@cjfields Since the BioPerl tarball is not contained in the original source of minicpan, I downloaded the tar.gz file from the [http://www.cpan.org/authors/id/C/CJ/CJFIELDS/](url), and add this file to the minicpan sources as a extended minicpan database.

**Comment by cjfields** [comment]
@SilentGene how are you specifically trying to install Bioperl?  A standard `cpanm Bio::Perl` should work:

http://bioperl.org/INSTALL.html

If you are trying to perform a local installation I recommend using `local::lib` or perlbrew

**Comment by cjfields** [comment]
@SilentGene I'm closing this issue out as we can't replicate the problem.  Feel free to reopen it if you can provide more specific details on the problem.
