### ISSUE TITLE
fix triggering the Docker Hub image build to only occur once per Travis CI build array

### ISSUE THREAD

**Issue by hlapp** [bioperl/bioperl-live#242]
The Docker Hub image build is retriggered after a succeeding Travis CI build. So that this occurs only once per full build array, the script tests whether Perl is v5.18 (because that's the version that the container uses).

Obviously, with the partitioning of BioPerl tests under Perl v5.18 this now triggers once per partition, which. albeit not outright wrong, only serves to waste resources on Docker Hub.

Some possibilities for fixing this:
1. Change the partitioned test array to use a different version of Perl than v5.18.
2. Change the version of Perl for triggering the Docker Hub build to a version of Perl different from v5.18. Obviously. we should then also correspondingly change the version of Perl used in the Docker image.
3. Narrow the trigger condition by testing for a certain partition, or for no partition defined.

None of these are difficult to implement. However, ideally we trigger the Docker Hub image build only when all tests pass, and it seems that none of the options above would truly accomplish that?

It seems that ideally we would want to trigger after the last partition succeeds,  provided that all previous partitions succeeded as well. I don't think that's possible to program into the triggering shell script; for example, given the parallel execution of the builds in the matrix, there's no guarantee that the last partition would even finish before the others do.

So I'm looking for input - thoughts and/or recommendations on how best to trigger the Docker image rebuild, where we'd have the best assurance of tests passing.

**Comment by zmughal** [comment]
The [4th build](https://travis-ci.org/bioperl/bioperl-live/jobs/263552509) is 5.18 without any code coverage. That should restore any previous behaviour. Just check that the COVERAGE environment variable is empty.

**Comment by hlapp** [comment]
So it's really just the code coverage that needed the partitioning to avoid Travis timeouts? Indeed it'd be easy to add that test to the condition.

**Comment by zmughal** [comment]
Yep! Enabling code coverage slows down the tests, but in the normal case, it is quite speedy.

In fact, we can make the builds run even faster if we cache the Perl dependencies. If anybody is interested in having that, I can make a PR for that change. It would just be adding

```yaml
cache:
  directories:
    # local::lib caching
    - $HOME/perl5
```

to `.travis.yml`.

**Comment by hlapp** [comment]
> In fact, we can make the builds run even faster if we cache the Perl dependencies. If anybody is interested in having that, I can make a PR for that change.

That'd be cool if you can make that work. Even if it doesn't save us from having to use the partitioning, not using resources on Travis CI (which we are using for free) unnecessarily is certainly a worthwhile effort.

**Comment by zmughal** [comment]
PR #244 should fix this.

**Comment by zmughal** [comment]
There is another alternative way that might be useful to know about in the future: <https://blog.travis-ci.com/2017-05-11-introducing-build-stages>. These would let all test builds run and then move to the stage that does the Docker Hub deployment.

**Comment by hlapp** [comment]
> There is another alternative way that might be useful to know about in the future: https://blog.travis-ci.com/2017-05-11-introducing-build-stages.

Very cool indeed. I couldn't see when this would be available broadly - we should definitely consider switching to that once it's available.

**Comment by zmughal** [comment]
I saw an example using build stages with the Bokeh project <https://github.com/bokeh/bokeh/pull/6542>.
