### ISSUE TITLE
Parsing XMFA sequence name

### ISSUE THREAD

**Issue by fgvieira** [bioperl/bioperl-live#246]
Dear all,

I've been trying to read a XMFA file with Bioperl but I'm getting an error:

> ------------- EXCEPTION -------------
> MSG: Line does not comform to XMFA format:
> \>TelAviv_01:1-86 + TelAviv_01
 
Looking through the code it seems it is because of a regexp that expects a space character after the '>' followed by one or more numbers. Is that what XMFA format expects? Looking around ([here](http://bioperl.org/formats/alignment_formats/XMFA_multiple_alignment_format.html) and [here](http://darlinglab.org/mauve/user-guide/files.html)) I got the feeling it can be any sequence name...

thanks,

**Comment by bosborne** [comment]
@fgvieira Can you supply your code and the XMFA file that shows this bug?

**Comment by fgvieira** [comment]
You can reproduce it with:

> echo -e ">TelAviv_01:1-9 + TelAviv_01\nAAAAAAAAA" | perl -MBio::AlignIO -e '$in_file_h = Bio::AlignIO->new(-fh => \\*STDIN, -format => "xmfa"); $in_file_h->next_aln()'

**Comment by bosborne** [comment]
@fgvieira This looks to be the most definitive page:

http://darlinglab.org/mauve/user-guide/files.html

What it says is that the id after the ">" has to be a number, can't be a string like "TelAviv_01". The regex in xmfa.pm also shows this:

      m{^>\s*\d+:(\d+)-(\d+)\s([+-]{1})(?:\s+(\S+)\s*(\S\.*)?)?} ) 

Note that spaces are allowed after the ">".

**Comment by fgvieira** [comment]
But does it really need to be a number? I mean, on the link you provide, they say that each "[...] sub-alignment consists of one FastA format sequence entry per genome where [...]" and fasta headers accept letters and other characters. Furthermore, on other places (like [here](http://www.stats.ox.ac.uk/~didelot/files/xmfa2struct.pdf)) they also allow for sequence IDs.

tried looking on the webpage of the original creator of the format (Michael Brudno), but could not find anything...

**Comment by bosborne** [comment]
The page above does show this:

      >seq_num:start1-end1 ± comments (sequence name, etc.)

So Michael Brudno is saying this should be a number, and that the sequence name (presumably he means sequence id) can be put at the end of the header. I'm not familiar with the rationale behind the format, and why he wanted to number the entries this way.

**Comment by bosborne** [comment]
@fgvieira I'm going to close this issue, because Michael Brudno's text, above, is indicating that ">" is followed by a number, presumably Mauve or some application expects this.
