### ISSUE TITLE
How can I inatall Bioperl without internet connection & root

### ISSUE THREAD

**Issue by DasSKim** [bioperl/bioperl-live#249]
Hi
I'm installing Bioperl on my system which does not provide internet connection.
So I cannot use cpan to install Bioperl.
And I'm not the root user.
Perl version 5.8.8 is installed on this machine.
But there was no Module::Build 0.42>V to run build for Bioperl.
I tried to install Module::Build with default perl but it failed because I could not access root files.
So I installed another version of perl with prefix,  but did not work with following error.

$ ./Build
Can't locate Perl/OSType.pm in @INC (@INC contains: t/lib t/bundled lib /home01/x1477hyk/CREST/perl10/lib/5.10.1/x86_64-linux /home01/x1477hyk/CREST/perl10/lib/5.10.1 /home01/x1477hyk/CREST/perl10/lib/site_perl/5.10.1/x86_64-linux /home01/x1477hyk/CREST/perl10/lib/site_perl/5.10.1 .) at lib/Module/Build.pm line 17.
BEGIN failed--compilation aborted at lib/Module/Build.pm line 17.
Compilation failed in require at ./Build line 42.
BEGIN failed--compilation aborted at ./Build line 42.

Is there any way to install Bioperl on this condition?
Please help me.

Thanks
Dan

**Comment by cjfields** [comment]
@DasSKim Make sure you review the documentation:

http://bioperl.org/INSTALL.html

This discusses your particular use case, and how to run a local installation using `local::lib`.
