### ISSUE TITLE
Bio::SearchIO is incompatible with Fasta 3.6 (current major version)

### ISSUE THREAD

**Issue by lokapal** [bioperl/bioperl-live#255]
Error message:
```
------------- EXCEPTION: Bio::Root::Exception -------------
MSG: Unrecognized alignment line (3) '>--'
STACK: Error::throw
STACK: Bio::Root::Root::throw /usr/local/share/perl/5.18.2/Bio/Root/Root.pm:447
STACK: Bio::SearchIO::fasta::next_result /usr/local/share/perl/5.18.2/Bio/SearchIO/fasta.pm:1148
STACK: ./bin/find_invariable.pl:69
-----------------------------------------------------------
```
Indeed, Fasta 3.5 never produces second alignment with name '>--' but Fasta 3.6 sometimes does! It breaks Bio::SearchIO

**Comment by pcantalupo** [comment]
Please post necessary input and output files and a description of how to exactly reproduce this. Thank you

**Comment by lokapal** [comment]
Surely. Here you go:
`DESCRIPTION
 SSEARCH performs a Smith-Waterman search
 version: 36.3.8f May, 2017`

Database:
`>Database                                                                                                                            
AGAATTTGGAATTCCCTACAATCCCCAAAGTCAAG                                                                                                                   
GAGTAGTGGAGTCTATGAATAAGGAATTAAAGAAA                                                                                                                   
ATTATAGGGCAGGTAAGAGAGCAAGCTGAA `

Query:
`>query7271.26                                                                                                                                             
AGAATTTGGAATTCCCTACAATCCCCTAGAATTTGGAATTCCCTACAATCCCCTAGAATT                                                                                          
TGGAATTCCCTACAATCCCCTAGAATTTGGAATTCCCTACAATCCCCAAAGTCAAGGAGT                                                                                          
AGTGGAGTCTATGAATAAGGAATTAAAGAA`

Commandstring:
`ssearch36 -3 -E 0.01 -z 11 -q -n database.fa query.fa > output` 

Output file attached
[output.txt](https://github.com/bioperl/bioperl-live/files/1502467/output.txt)

**Comment by pcantalupo** [comment]
The problem is occurring during parsing of the first HSP. The HSP prematurely ends with the following lines:

```
              100
A3_100 GCAAGCTGAA

>--
```

Notice that there is no hit sequence line (line #3 in the algorithm). This is indicated by the error output `MSG: Unrecognized alignment line (3) '>--'`. Code needs updated to end HSP processing if a `-->` is found in this situation. I'll try to submit a fix soon.

**Comment by cjfields** [comment]
@lokapal if you can, attach an example test file for @pcantalupo to debug this issue (see the 'Attach files by dragging and dropping' link just below the reply box

**Comment by pcantalupo** [comment]
Hi all, No need to attach any files. I have what I need. I have a simple code fix but need to write a few tests. Too bogged down with other projects, etc... I will get this done by the end of next week.

**Comment by cjfields** [comment]
@pcantalupo no hurries, I just wanted to make sure you had everything you might need

**Comment by pcantalupo** [comment]
@lokapal the issue should be fixed. Reopen issue if there are any problems.
