### ISSUE TITLE
Bio::Tools::CodonTable is out of date

### ISSUE THREAD

**Issue by CathiZeil** [bioperl/bioperl-live#256]
The module currently uses a codon table version from 2013. The codon table has been updated in Nov, 2016 ([https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi](https://www.ncbi.nlm.nih.gov/Taxonomy/Utils/wprintgc.cgi)).

Currently there are 6 codon tables that are not included in the module (26-31). Additionally, the codon table with the id 15 seems to have been removed.

**Comment by heikkil** [comment]
I'll update Bio::Tools::CodonTable in the repo.
