### ISSUE TITLE
Bio::Tree:DistanceFactory typos?

### ISSUE THREAD

**Issue by mihkelvaher** [bioperl/bioperl-live#270]
I'm running BioPerl locally (`use lib './BioPerl..';`) and got this error:
`Bio::Tree::DistanceFactory::_nj: Can't locate object method "add_Descendents" via package "Bio::Tree::Node" `

Starting with line 199:
`      for my $nm ( @names ) {
	   $root->add_Descendents( Bio::Tree::Node->new(-id => $nm,
							-branch_length => $d));
       }
       return Bio::Tree::Tree(-root => $root);`

Bio::Tree::Node does not have a add_Descendent**s** sub, but it has add_Descendent sub, removing the "s" fixed it.

Then this came up a couple of lines further down in return:
`Bio::Tree::DistanceFactory::_nj: Undefined subroutine &Bio::Tree::Tree called`
Which got fixed by adding "->new"

changing
`return Bio::Tree::Tree(-root => $root);`
to
`return Bio::Tree::Tree->new(-root => $root);`

Might be typos or might be the way I'm running it.

**Comment by cjfields** [comment]
Nope, these were definitely in-code typos!  

https://github.com/bioperl/bioperl-live/blob/5de807925c95521209a89b6ca97dde45867aa7e3/Bio/Tree/DistanceFactory.pm#L200

https://github.com/bioperl/bioperl-live/blob/5de807925c95521209a89b6ca97dde45867aa7e3/Bio/Tree/DistanceFactory.pm#L203

**Comment by cjfields** [comment]
@mihkelvaher by the way, thx for pointing that out!
