### ISSUE TITLE
edit usage for Bio::MolEvol::CodonModel.pm

### ISSUE THREAD

**Issue by jayoung** [bioperl/bioperl-live#274]
hi there,

a tiny thing about the documentation for Bio::MolEvol::CodonModel.pm - currently the SYNOPSIS line 23 reads:
my ($ns, $syn) = $codon_path->{'AATAAC'};

looks like it needs to be unreferenced, so maybe edit that line to: 
my ($ns, $syn) = @{$codon_path->{'AATAAC'}};

that fix works for me, at least.  I came across this while trying to troubleshoot something else - it's possible I'll be asking for some help on that later if I can't figure it out myself...

thanks very much,

Janet

------------------------------------------------------------------- 

Dr. Janet Young 

Malik lab
http://research.fhcrc.org/malik/en.html

Division of Basic Sciences
Fred Hutchinson Cancer Research Center
1100 Fairview Avenue N., A2-025, 
P.O. Box 19024, Seattle, WA 98109-1024, USA.

tel: (206) 667 4512
email: jayoung  ...at...  fredhutch.org

-------------------------------------------------------------------

**Comment by carandraug** [comment]
Thank you. I have pushed the change.

**Comment by jayoung** [comment]
thanks!
