### ISSUE TITLE
suggestion for wiki page https://bioperl.org/howtos/PopGen_HOWTO.html

### ISSUE THREAD

**Issue by jayoung** [bioperl/bioperl-live#276]
hi there,

sorry to bombard you all this afternoon.     I have a suggestion for the wiki page https://bioperl.org/howtos/PopGen_HOWTO.html

I just spent a little time trying to get Bio::PopGen::Statistics->mcdonald_kreitman to work and was getting mysterious error ("cannot get path for TC").  I finally tracked it down and it was a very simple error on my part, just not very obvious to me. I had created a population object from an alignment but I had been treating it as individual nucleotides rather than codons.

Here's my suggestion: in the section of that wiki page titled 
"Allele data from Alignments using Bio::AlignIO and Bio::PopGen::Utilities"
in the second code block, maybe add something like this:

```
# to treat the alignment as protein coding (e.g. to prepare data for mcdonald_kreitman function)
my $pop = Bio::PopGen::Utilities->aln_to_population(-alignment=>$aln,
                                                    -site_model => 'cod');
```

I'm really happy I can do MK tests in perl now - thank you! 

Janet

**Comment by carandraug** [comment]
Thank you for the suggestion. The bioperl website has its own repository. Can you please open a pull request on the site repository https://github.com/bioperl/bioperl.github.io ?
