### ISSUE TITLE
how to remove a marker from a population?

### ISSUE THREAD

**Issue by jayoung** [bioperl/bioperl-live#277]
hi there,

Me again.  I'm not sure if this is a request for help, or a suggestion for an enhancement to Bio::PopGen::Population.   

I'm running some McDonald-Krietman tests, and I'd like to filter out rare polymorphisms before I do the test.  I can see how to iterate through the markers and get allele frequencies, but I can't find a straightforward way to remove markers from my Bio::PopGen::Population object.   

It looks like I could probably iterate through each individual in the population, and then iterate through each genotype, checking against a list of marker names that I want to remove (using remove_Genotype to actually do it). But I'm wondering if I'm missing a simpler way (or if it would be possible to implement something?).

I'm also happy to take suggestions on other commandline/R tools to do this. 

thanks for any suggestions!

Janet

**Comment by cjfields** [comment]
Paging @hyphaltip

**Comment by cjfields** [comment]
As a note, @carandraug is moving the PopGen modules into a separate repository for separate release.

**Comment by hyphaltip** [comment]
Not sure there is a delete or remove function built in So sounds like one would be helpful.

N.b, In general this code is going to be slower than what you can do in other tools so I’d use caution committing to this package if you need to do a lot.

How much you invest here vs trying some R or python solutions or manipulation of data in plink.

Jason Stajich, PhD
jasonstajich.phd@gmail.com

**Comment by hyphaltip** [comment]
This issue was moved to bioperl/Bio-PopGen#3
