### ISSUE TITLE
Issue in a command while preparing to install Bioperl

### ISSUE THREAD

**Issue by Shubham-Bioinformatician** [bioperl/bioperl-live#278]
![capture](https://user-images.githubusercontent.com/42505734/44305109-6e3ce180-a38d-11e8-82a4-096ac80be6c6.PNG)
Please suggest..

**Comment by heikkil** [comment]
Not a bioperl problem, but you mistyped Module::Build. There is an extra d.

**Comment by Shubham-Bioinformatician** [comment]
Oops, Thankyou very much.
