### ISSUE TITLE
Why was the 'blastxml' driver for SearchIO removed?

### ISSUE THREAD

**Issue by sestaton** [bioperl/bioperl-live#279]
The `Bio::SearchIO::blastxml` module has been used for years to parse NCBI XML BLAST output, but it seems to have been removed in the latest release. This class is still referred to in the `Bio::SearchIO::blast` documentation though it does not appear to exist on CPAN or Github now, unless I'm missing something.

URL: https://metacpan.org/pod/Bio::SearchIO::blast#DESCRIPTION

Can we add this back if it was indeed removed? This module was stable and I have code that depends on it. If there is a new way to parse XML output of BLAST it would be helpful to know.

Thanks.

**Comment by sestaton** [comment]
For reference, this change appears to have been made on the 1.7x change according to this issue:

**Comment by cjfields** [comment]
@sestaton We are working on splitting out modules that have additional dependencies, such as BLASTXML.  It **is** on CPAN: https://metacpan.org/pod/Bio::SearchIO::blastxml

This should install by directly requesting the module, so using `cpanm`:

```
cpanm Bio::SearchIO::blastxml
```

Let us know if this doesn't work for you.

**Comment by cjfields** [comment]
Just tested this locally:

```
cpanm Bio::SearchIO::blastxml
--> Working on Bio::SearchIO::blastxml
Fetching http://www.cpan.org/authors/id/C/CJ/CJFIELDS/Bio-SearchIO-blastxml-1.70.tar.gz ... OK
Configuring Bio-SearchIO-blastxml-1.70 ... OK
Building and testing Bio-SearchIO-blastxml-1.70 ... OK
Successfully installed Bio-SearchIO-blastxml-1.70
1 distribution installed
```

**Comment by sestaton** [comment]
Thanks for the quick response. That is all I need. I just happened to notice this change when building a docker image for a package and the module couldn't be found.

**Comment by cjfields** [comment]
Not a problem; if anything this indicates we should update the installation docs to reflect this more directly.
