### ISSUE TITLE
Check/Update installation documentation

### ISSUE THREAD

**Issue by cjfields** [bioperl/bioperl-live#280]
We should update installation docs to make sure modules that are released separately on CPAN have an installation path.

**Comment by carandraug** [comment]
Let's remove all installation documentation instead. I just took a look at the documentation and it even includes documentation on how to install perl on the system.  There's plenty of pages on the internet that cover it, better than we can. Let's rely on it instead.

Also, how to install is an opinion. I disagree very much with the current install instructions which highly recommend perlbrew.

**Comment by cjfields** [comment]
I don't agree that we should remove all installation instructions, but it could definitely be simplified and consolidated to one location.  `perlbrew` is IMHO more useful for developers, so it could easily go.

**Comment by carandraug** [comment]
Done now. Check out `README` for users and `HACKING` for those interested in development.
