### ISSUE TITLE
Installing using cpanm fails

### ISSUE THREAD

**Issue by hlapp** [bioperl/bioperl-live#289]
The bioperl/bioperl container image fails to build with the following error message:

```
Entering bioperl-live-master
Configuring bioperl-live-master ... N/A

The distribution doesn't have a proper Makefile.PL/Build.PL See /root/.cpanm/work/1538087441.6/build.log for details.
```

Note that the way the [respective Docker file](https://github.com/bioperl/bioperl-docker/blob/master/bioperl/Dockerfile) installs bioperl is simply this command (i.e., it does not by itself invoke Build.PL, or in fact anything other than `cpanm`):
```
cpanm -v https://github.com/bioperl/bioperl-live/archive/master.tar.gz
```

Is there some way that `cpanm` needs to be taught what to do instead of what it is trying to do right now?

**Comment by carandraug** [comment]
If you want to target this repo (instead of a release distribution), you will need to clone the git repo, then author a build, then install it. You will need a bunch of dependencies, modules that are only used to author a distribution but won't be needed at install and runtime.

**Comment by hlapp** [comment]
> If you want to target this repo (instead of a release distribution), you will need to clone the git repo, then author a build, then install it.

So what you're saying is that cpanm can't be used to install BioPerl from source, right?

> You will need a bunch of dependencies, modules that are only used to author a distribution but won't be needed at install and runtime.

Can you spell this out in terms of commands that need to be issued? (If you prefer, you'd also welcome to send a pull request for the Docker file linked above.) The dependencies aren't a problem, so long as they can be installed through cpanm, apt, and similar means. I assume they can?

**Comment by hlapp** [comment]
> So cpanm won't see a Makefile.pl or Build.pl in the main repo. I guess your cpanm command should either target the latest release archive, or you could use `cpanm Bio::Perl`. Unless it's absolutely necessary for the docker image to use the latest commit to master?

@yzhernand yes, that's the meaning of the`:latest` tag of the `bioperl/bioperl` container image. I.e., it is to be built off of the current master branch, and is automatically rebuilt whenever there's a change on master.

**Comment by hlapp** [comment]
> But you need to prepare/author/etc the sources. The git repository is the source code for the distribution, it's not the distribution itself.

So how do I do this? It seems hard to figure this out from the Dist::Zilla documentation (at least for someone like me who is entirely unfamiliar with it).

> It's just latest often means the latest release. Not the last commit on the development sources.

Yes sometimes it does. In the past for BioPerl the latest release wasn't what most people were running (because the latest release was way too old); instead they were running off of master. This may conceivable (or hopefully) change in the future, and then it might be better to have the image built off of master tagged `:devel` or something. But there'll presumably always be an image built off of master, so the question I pose here won't go away.

**Comment by carandraug** [comment]
>> You will need a bunch of dependencies, modules that are only used to author a distribution but won't be needed at install and runtime.
> Can you spell this out in terms of commands that need to be issued? (If you prefer, you'd also be welcome to send a pull request for the Docker file linked above.) The dependencies aren't a problem, so long as they can be installed through cpanm, apt, and similar means. I assume they can?

Assuming you have dzil, you can run `dzil authordeps` to get a list of the dependencies to author releases. In the case of BioPerl, that's:

    $ dzil authordeps
    Dist::Zilla::PluginBundle::BioPerl
    Software::License::Perl_5

You can pipe that to cpanm to install. Then you can either install or build the distribution with `dzil build` and `dzil install`.

The BioPerl PluginBundle has a lot of dependencies.  All of them are on CPAN.  I prefer to install things via apt so I have packaged all of them for Debian.

**Comment by hlapp** [comment]
There is in fact a separate container image collecting all the BioPerl dependencies (`bioperl/bioperl-deps`) ([Dockerfile](https://github.com/bioperl/bioperl-docker/blob/master/bioperl-deps/Dockerfile)), and the `bioperl/bioperl` image is based off of it. _(The idea is that everyone who needs a custom BioPerl container can build it off the same common dependencies container image as the official BioPerl container.)_ As you can see, it's based off of Ubuntu. (I suppose I need to switch that to 16.04 within the next couple of months as 14.04 reaches EOL in April next year.) I wouldn't have any objections to switching that to Debian proper. (Ubuntu simply seemed much more common in the scientific computing environments I've experienced, for whatever reason.)

You'll see that I use cpanm for the CPAN dependencies, though for those needing native libraries I install those first via apt, because it's resulted in fewer (in fact no) problems.

**Comment by hlapp** [comment]
BTW just for the record, it's `bioperl/bioperl:stable` that's the Docker image built from the latest release on CPAN. Rebuilding it gets kicked off whenever there is a new release tagged in BioPerl.

**Comment by carandraug** [comment]
Well, looks like there's nothing left to be done here, so I'm closing the issue.
