### ISSUE TITLE
Installation using Dist::Zilla fails

### ISSUE THREAD

**Issue by hlapp** [bioperl/bioperl-live#291]
Here are the steps I performed. (These were on top of the current bioperl/bioperl-deps Docker container, which is based on Ubuntu 14.04.):

```bash
curl -L -s -o - https://github.com/bioperl/bioperl-live/archive/master.tar.gz | tar zxvf -
cd bioperl-live-master/
cpanm Dist::Zilla
apt-get update -y && apt-get install -y git  # apparently BioPerl's Dist::Zilla plugin depends on this
dzil authordeps | cpanm
dzil install
```

The failure is the following (after a long list of actions printed to the screen, which did not seem to include any failures, and which I am therefore omitting here):

```
--> Working on .
Configuring BioPerl-1.7.3 ... OK
==> Found dependencies: Bio::DB::GenBank, Bio::DB::EMBL, Bio::DB::Ace, Bio::DB::GenPept, Cache::FileCache, Bio::Tools::Run::Ensembl, Win32
--> Working on Bio::DB::GenBank
Fetching http://www.cpan.org/authors/id/C/CJ/CJFIELDS/BioPerl-1.007002.tar.gz ... OK
Configuring BioPerl-1.007002 ... OK
Building and testing BioPerl-1.007002 ... OK
Successfully installed BioPerl-1.007002
--> Working on Bio::DB::Ace
Fetching http://www.cpan.org/authors/id/C/CJ/CJFIELDS/Bio-DB-Ace-1.7.3.tar.gz ... OK
Configuring Bio-DB-Ace-1.7.3 ... OK
==> Found dependencies: Ace::Sequence::Homol, Ace
--> Working on Ace::Sequence::Homol
Fetching http://www.cpan.org/authors/id/L/LD/LDS/AcePerl-1.92.tar.gz ... OK
Configuring AcePerl-1.92 ... OK
==> Found dependencies: Cache::Cache
--> Working on Cache::Cache
Fetching http://www.cpan.org/authors/id/R/RJ/RJBS/Cache-Cache-1.08.tar.gz ... OK
Configuring Cache-Cache-1.08 ... OK
==> Found dependencies: Digest::SHA1
--> Working on Digest::SHA1
Fetching http://www.cpan.org/authors/id/G/GA/GAAS/Digest-SHA1-2.13.tar.gz ... OK
Configuring Digest-SHA1-2.13 ... OK
Building and testing Digest-SHA1-2.13 ... OK
Successfully installed Digest-SHA1-2.13
Building and testing Cache-Cache-1.08 ... OK
Successfully installed Cache-Cache-1.08
Building and testing AcePerl-1.92 ... FAIL
! Installing Ace::Sequence::Homol failed. See /root/.cpanm/work/1538259574.30271/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'Ace' is not installed, Module 'Ace::Sequence::Homol' is not installed
! Bailing out the installation for Bio-DB-Ace-1.7.3.
--> Working on Bio::Tools::Run::Ensembl
Fetching http://www.cpan.org/authors/id/C/CJ/CJFIELDS/BioPerl-Run-1.007002.tar.gz ... OK
Configuring BioPerl-Run-1.007002 ... OK
Building and testing BioPerl-Run-1.007002 ... FAIL
! Installing Bio::Tools::Run::Ensembl failed. See /root/.cpanm/work/1538259574.30271/build.log for details. Retry with --force to force install it.
--> Working on Win32
Fetching http://www.cpan.org/authors/id/J/JD/JDB/Win32-0.52.tar.gz ... OK
Configuring Win32-0.52 ... N/A
! Configure failed for Win32-0.52. See /root/.cpanm/work/1538259574.30271/build.log for details.
! Installing the dependencies failed: Module 'Win32' is not installed, Module 'Bio::Tools::Run::Ensembl' is not installed
! Bailing out the installation for BioPerl-1.7.3.
3 distributions installed
[DZ] error running {{["cpanm", "."]}}
[DZ] install failed, left failed dist in place at .build/LnK2FRiHiG
[DZ] error running {{["cpanm", "."]}} at inline delegation in Dist::Zilla for logger->log_fatal (attribute declared in /usr/local/share/perl/5.18.2/Dist/Zilla.pm at line 768) line 18.
```

So there seem to be two problems here, one is that installing BioPerl 1.7.3 (the version on the master branch) from source creates a dependency on also installing BioPerl 1.7.2 from CPAN, which doesn't seem right. The other is it tries to configure for Windows when running on a Linux Ubuntu machine.

**Comment by carandraug** [comment]
> So there seem to be two problems here, one is that installing BioPerl 1.7.3 (the version on the master branch) from source creates a dependency on also installing BioPerl 1.7.2  from CPAN, which doesn't seem right.

That's not really what's happening. The issue is you are trying to install something that has not been released yet and is also dependent on things not yet released. In this specific case, it is dependent on a bunch of `Bio::DB::` that have been moved into their own distribution but not yet released (@pyrimidie has been making their releases but this takes time).

However, there's another issue which is that we have scripts that are dependent on modules that have been moved out. In most cases, I moved the scripts with the associated modules but this does not always makes sense. For example `bp_fetch`, which is what's causing those dependencies, does not have a core dependency that makes sense to be moved with.

> The other is it tries to configure for Windows when running on a Linux Ubuntu machine.

Should now be fixed.

**Comment by hlapp** [comment]
So this sounds like I need to hang on and wait a little longer until I should expect this to succeed cleanly. Is there an issue that I should be tracking and that, when closed, would indicate that it's ready?

Tagging @cjfields here again. (I also edited the reference in your comment.)

**Comment by carandraug** [comment]
I have changed `bp_fetch` a bit and made its depency on `Bio::DB::*` a suggestion. Testing on Debian buster installs fine without looking for any other `Bio` modules.

The only other issue during installation are some failing tests. The only failing tests are issue #292 and issue #293 which were failing before but I'm guessing you were not running the test suite before or were disabling the network tests. You can skip tests requiring network by setting `NO_NETWORK_TESTING` as described in [Test::RequiresInternet](`https://metacpan.org/pod/Test::RequiresInternet`) (but it's better if you didn't since then we would have knew about this issues ages ago)

**Comment by hlapp** [comment]
> The only failing tests are issue #292 and issue #293 which were failing before but I'm guessing you were not running the test suite before or were disabling the network tests.

Remember I didn't do anything other than using cpanm, without any additional command line switches other than `-v` . So I _was_ running the tests (because that's cpanm's default if you don't turn it off). and I wasn't disabling any tests other than those that were disabled by default.

I assume (some of?) the environment variables that previously controlled which tests weren't being run by default are now absent (or different) with the change to Dist::Zilla.

Indeed the log from the last successful container build on Docker Hub before the start of the migration includes just prior to the tests output the following line:
```
  - will not run internet-requiring tests
```
and subsequently various tests report `skipped: Network tests have not been requested`. So your hypothesis that network tests haven't been run for a while is I think correct, but the reason was that this was the default, and instead one had to do something to enable them (which I didn't).

**Comment by hlapp** [comment]
Just gave it a test. Indeed BioPerl itself doesn't pull in the 1.7.2 CPAN dependency anymore. But Bio::ASN1::EntrezGene does (which the container installs after BioPerl):
```
Configuring Bio-ASN1-EntrezGene-1.73 ... OK
==> Found dependencies: Bio::Cluster::SequenceFamily
--> Working on Bio::Cluster::SequenceFamily
Fetching http://www.cpan.org/authors/id/C/CJ/CJFIELDS/BioPerl-1.007002.tar.gz ... OK
Configuring BioPerl-1.007002 ... OK
Building and testing BioPerl-1.007002 ... OK
Successfully installed BioPerl-1.007002
```
So maybe the best approach to that is to remove Bio::ASN1::EntrezGene from the container for now. It's rarely used anyway.

**Comment by carandraug** [comment]
> So maybe the best approach to that is to remove Bio::ASN1::EntrezGene from the container for now. It's rarely used anyway.

That will be a dependency of Bio-EUtilities , not sure if that is also being installed.

**Comment by cjfields** [comment]
@carandraug Bio::ASN1::EntrezGene shouldn't be a dependency of the Bio-EUtilities _modules_, but it's possible a script may require it.  

I hate dependency creep...

**Comment by carandraug** [comment]
> @carandraug Bio::ASN1::EntrezGene shouldn't be a dependency of the Bio-EUtilities modules, but it's possible a script may require it.

The default retmode when fetching from gene is `asn1`

**Comment by cjfields** [comment]
@carandraug that should return the data in ASN1 format, but it's a raw stream and not parsed (so shouldn't require Bio::ASN1::EntrezGene).  That was intentional, I didn't want to couple formats-specific parsers with the eutils interface.

**Comment by carandraug** [comment]
you, you're right. It's then used `bp_genbank_ref_extractor` to actually parse the sequences.
