### ISSUE TITLE
deprecating Bio::Root::RootI::deprecate

### ISSUE THREAD

**Issue by carandraug** [bioperl/bioperl-live#294]
While fixing an issue with Bioperl versions, I came accross `Bio::Root::Root::deprecate` which I think we're better off without (but then again, I'm not sure what problem it was meant to solve). The function allows to deprecate things starting in a future version and to throw an error after a specific version.

About deprecating in the future, if we are deprecating things then they are deprecated, they won't become deprecated in the future.

About giving an error after a specific error, that's pretty mean. The code is there, it should have been removed but for some reason was not, and we throw an error.

It also has issues with comparing versions which no longer work correctly since our version numbers are now '1.7.3' for example.

**Comment by carandraug** [comment]
Ok. I have now deprecated it with  2cbe459 . I couldn't be bothered with finding how to silence the deprecation warnings during the tests of `deprecated` while at the same time, testing that the warnings tests were being triggered. So I just removed the tests for `deprecated`.

**Comment by cjfields** [comment]
Works for me!
