### ISSUE TITLE
Simplify Bio::DB::IndexedBase?

### ISSUE THREAD

**Issue by cjfields** [bioperl/bioperl-live#305]
This may solve a lot of funky issues seen springing up with BioPerl over the last few years.  From a user:

> On a side note, if you are trimming BioPerl fat, there is one function in Bio::DB::IndexedBase, the _strip_crnl function, that has a call out to Inline:C that does not add any performance benefit over perls own '=~ 
> tr///‘
> operator (it does compared to regular expressions), but the
> Inline::C on the fly C compilation does seem to generate weird
> behavior on some systems (especially if you do any
> parallelization). I’ve started stripping it out of all our local
> BioPerl installations just for that reason.

**Comment by cjfields** [comment]
For context, this comes from a developer on a non-CPAN tool, MAKER.

**Comment by carsonhh** [comment]
I have submitted a pull request with changes for this --> https://github.com/bioperl/bioperl-live/pull/309

**Comment by cjfields** [comment]
This is merged, closing the ticket.
