### ISSUE TITLE
Can't locate object method "new" via package "Bio::Search::HSP::GenericHSP::SUPER"

### ISSUE THREAD

**Issue by carandraug** [bioperl/bioperl-live#307]
There are multiple cpantesters reporting the following failure:

```
Can't locate object method "new" via package "Bio::Search::HSP::GenericHSP::SUPER" at /usr/home/cpan/pit/bare/conf/perl-5.14.2/.cpanplus/5.14.2/build/z3V70sjNdA/BioPerl-1.7.4/blib/lib/Bio/Search/HSP/GenericHSP.pm line 182, <GEN1> line 2564.
# Looks like your test exited with 255 just after 7.
t/SearchIO/Tiling.t ................. 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1134/1141 subtests 
```

I'm so far unable to reproduce it though.

**Comment by cjfields** [comment]
I think this is an issue with use of indirect object declaration, e.g. http://modernperlbooks.com/mt/2009/08/the-problems-with-indirect-object-notation.html

The test file seems to have a few examples of this, but it could be elsewhere in the code.
