### ISSUE TITLE
Enable TblastN parsing

### ISSUE THREAD

**Issue by FredericBGA** [bioperl/bioperl-live#312]
Can we safely replace this:
https://github.com/bioperl/bioperl-live/blob/7cc47700c5ee5aed5e6a32966b86628c28b6b127/lib/Bio/SearchIO/Writer/GbrowseGFF.pm#L208
by: 
`$self->throw("This module only works on (T)BLASTN reports at this time.  Sorry.\n") unless $source =~ /BLASTN/; `
It seems to work well on TblastN as well.

**Comment by cjfields** [comment]
Fixed, thanks for the update!
