### ISSUE TITLE
MapTiling Root Exception error

### ISSUE THREAD

**Issue by ghanashyamchalla** [bioperl/bioperl-live#318]
------------- EXCEPTION: Bio::Root::Exception -------------
MSG: Undefined sub-sequence (441,441). Valid range = 1 - 441
STACK: Error::throw
STACK: Bio::Root::Root::throw /anaconda3/lib/site_perl/5.26.2/Bio/Root/Root.pm:447
STACK: Bio::Search::HSP::HSPI::matches_MT /anaconda3/lib/site_perl/5.26.2/Bio/Search/Tiling/MapTileUtils.pm:611
STACK: Bio::Search::Tiling::MapTiling::_calc_stats /anaconda3/lib/site_perl/5.26.2/Bio/Search/Tiling/MapTiling.pm:1163
STACK: Bio::Search::Tiling::MapTiling::length /anaconda3/lib/site_perl/5.26.2/Bio/Search/Tiling/MapTiling.pm:508

Is this something to do with the BioPerl recent changes? or something with my usage?

It throws error with this usage

my @contexts = $tiling->contexts('query');
my $context = pop @contexts;
my $align_length_query = $tiling->length('query', 'exact', $context);

**Comment by cjfields** [comment]
@ghanashyamchalla shouldn't be related to changes in the code base, the error is due to other issues.  @majensen would you have any idea on this one?

**Comment by majensen** [comment]
Hmm, looks like it's a zero length subsequence 441-441, which in some conventions is a length-1 subseq. @ghanashyamchalla do you have the blast rpt you were analyzing? I could try to debug.

**Comment by ghanashyamchalla** [comment]
[maptiling_error_blastp_xml.txt](https://github.com/bioperl/bioperl-live/files/3254681/maptiling_error_blastp_xml.txt)

@majensen  Here is the BLASTp output that is giving the error. 

Thanks
Ghana

**Comment by ghanashyamchalla** [comment]
Thank you @cjfields

**Comment by majensen** [comment]
@ghanashyamchalla I've identified the issue -- it is a non-obvious problem! 
The convention in NCBI blast output is that "from" -> "to" coordinates are always inclusive: so for a query sequence that is described
```
      <Hsp_query-from>1</Hsp_query-from>
      <Hsp_query-to>441</Hsp_query-to>
```
includes the aa at position 1 _and_ the aa at position 441 -- so the length of the sequence is 441-1+1 = 411 aas. All the tiling calculations make this assumption, and XML that is emitted by NCBI Blast follows this convention (based on my spot check).

It looks like the _diamond_ program follow a different convention, called "half-open", where the aa at the reported "to" position is _not_ included in the sequence. In this convention, the sequence length is just 441-1+0 = 440, one less than MapTiling expects based on the NCBI. The error you got was "lucky" in that it exposed this difference -- there was a "tile" of length 1 (441-441), tiling was looking for the 441st character in a seq with only 440 characters, and so barfed. This may be the only situation where you would see the issue -- all the rest of your hits are processed with no error (but they are all excluding the data of one site in the HSP alignment).

I expect that any summary results you have got in the past with MapTiling will be only very slightly different from actual. But it should be easy to post-process the _diamond_ output to make it MapTiling-friendly -- for all the XML elements with tags "Hsp_query-to" and "Hsp_hit-to", take the numeric value in the tag and subtract 1 from it. So the above example would become
```
      <Hsp_query-from>1</Hsp_query-from>
      <Hsp_query-to>440</Hsp_query-to>
```
Let me know if this makes sense.
Mark

**Comment by ghanashyamchalla** [comment]
Thanks Mark. Now it makes sense why only some queries had this error. Thanks alot for looking in to this.

**Comment by cjfields** [comment]
Just to follow up on this: I would suggest this is an issue with DIAMOND output that should be raised with their developer.  @ghanashyamchalla did you want to do this?  You could refer back to this issue and @majensen 's comment above.
