### ISSUE TITLE
t/00-compile.t fails without GD.pm

### ISSUE THREAD

**Issue by eserte** [bioperl/bioperl-live#323]
If GD.pm is not installed, then the test suite of BioPerl-1.7.6 fails:
```
#   Failed test 'bin/bp_chaos_plot compiled ok'
#   at t/00-compile.t line 589.
#          got: '512'
#     expected: '0'
Can't locate GD.pm in @INC (you may need to install the GD module) (@INC contains: ...  .) at bin/bp_chaos_plot line 8.BEGIN failed--compilation aborted at bin/bp_chaos_plot line 8. at t/00-compile.t line 598, <GEN1900> line 2.
# Looks like you failed 1 test of 513.
t/00-compile.t ...................... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/513 subtests 
```

**Comment by carandraug** [comment]
Confirmed. The GD dependency was made a suggestion instead of requirement because of issue #314 . But of course, if GD is missing the compile tests fail. Not sure how others want to address it. I lean on making GB a requirement again or kicking `bp_chaos_plot` out from core.

**Comment by bosborne** [comment]
It's also Bio::Align::Graphics that's using GD. My vote would be to remove them from the core. There are a few different ways to install the GD library itself these days, but I'm not sure that all users can easily do this install.

**Comment by carandraug** [comment]
> It's also Bio::Align::Graphics that's using GD.

Yeah, but that's already been removed from core since 1.7.3

**Comment by cjfields** [comment]
I vote we strip `bp_chaos_plot` from core.  Do we have a happy retirement home for little-used scripts?

**Comment by carandraug** [comment]
> I vote we strip bp_chaos_plot from core.

Done.

> Do we have a happy retirement home for little-used scripts?

No. It might be worth considering removing all scripts and have a separate distribution for them. I'd guess that at least some of the simpler ones could be implemented in p5-bpwrapper.

**Comment by cjfields** [comment]
I think those that only use core modules and no additional dependencies are probably harmless, but ones like `bp_chaos_plot` (though they may be useful) add unnecessary overhead, particularly with tricky-to-install modules like GD.
