### ISSUE TITLE
homepage in dist.ini 404s

### ISSUE THREAD

**Issue by mr-c** [bioperl/bioperl-live#330]
https://metacpan.org/release/BioPerl → HTTP 404 Not Found

**Comment by carandraug** [comment]
Interesting. I have asked on #metacpan what happened. I'm pretty sure this page used to exist.

**Comment by carandraug** [comment]
This is now fixed. Apparently the latest release for some reason failed to index. They have triggered it manually and now it is back up.

**Comment by mr-c** [comment]
@carandraug Thanks!

**Comment by carandraug** [comment]
Here's a more complete answer I got about what happened:

> you did nothing wrong, PAUSE indexed it correctly. it was just metacpan that seems to have only done half the job
>  wish I had better answers for you.  Sometimes we just need to take a second pass at indexing a dist.  I think we'd need more comprehensive logging to be able to answer that.
> Having said all that, we're quite happy to re-index things that go wrong.  It's not a big deal.

Basically, we did nothing wrong with our upload, and next time this or something similar happens, we just need to ask them.
