### ISSUE TITLE
Why version 1.7.7 is not a release?

### ISSUE THREAD

**Issue by serge2016** [bioperl/bioperl-live#332]
Hello!

Which version should I use? 1.7.2, that has a release tag, or 1.7.7, which is a new one?

**Comment by carandraug** [comment]
You should install from CPAN, the latest version is 1.7.7 see https://metacpan.org/release/BioPerl

If you want to install from development sources, you will need dzil and a bunch of development packages to prepare the distribution that you then can install. If you want to go that route, there you should use the BioPerl-v1.7.7 tag.

I see that github marks some tags as releases and not others, and 1.7.2 as the "latest release". No idea why. But github should not be the medium to distribute releases, so please ignore. Check cpan instead.
