### ISSUE TITLE
Can't locate object method "no_sequences" via package "Bio::SimpleAlign"

### ISSUE THREAD

**Issue by zhangleigloria** [bioperl/bioperl-live#342]
Hi, I had the following problem while running the perl script: Can't locate object method "no_sequences" via package "Bio::SimpleAlign"at ./PL_pipeline/betterSeq-seeds.pl line 113, <GEN0> line 175.
sub consensus{
        my $fl=$_[0];
        my $str = Bio::AlignIO->new(-file => $fl);
        my $aln = $str->next_aln();
        my $nice=0;
        my $nseq=$aln->no_sequences;
        if($nseq > 6){
                $nice=50;
        }else{
                $nice=30;
        }
How can I solve this problem? Thank you very much!

**Comment by hyphaltip** [comment]
The method is num_sequences()

You may also want to set a format for your reader when you initialize Bio::AlignIO not sure how good the guessing is.

https://metacpan.org/pod/Bio::SimpleAlign#num_sequences

**Comment by zhangleigloria** [comment]
Ok，it works.Thank you very much!
