### ISSUE TITLE
Where to find moved packages?

### ISSUE THREAD

**Issue by Stikus** [bioperl/bioperl-live#351]
Hello, I'm trying to move our [VEP](https://github.com/Ensembl/ensembl-vep) installation from bioperl `1.7.2` to latest `1.7.7`.
According to VEP test logs I'm missing `Bio::Tools::dpAlign`:
```
Error:  Can't locate Bio/Tools/dpAlign.pm in @INC
```
 and it is correct due to this [line](https://github.com/bioperl/bioperl-live/blob/master/Changes#L175) in `Changes`:
```
1.7.3     2019-01-30 13:30:34+00:00 Europe/London

    * The following modules have been removed from the BioPerl
      distribution to be part of a separate distribution.  They have
      been integrated into other module distributions for independent
      development:

          Bio::Align::Graphics
          ...
          Bio::Tools::dpAlign
          ...
          Bio::Variation::*
```

Where can I find current version of this package? I tried to look at CPAN and github but I cannot find any.

**Comment by carandraug** [comment]
Looking into the git logs, I've found it was removed with 2ea25ecc4fe5c4d6ed11cf8ba25db62c20a24102 which has this message:

    Move modules dependent on Bio::Ext::Align into defunct bioperl-ext
    
    This modules are an interface to Bio::Ext::Align which is part of the
    bioperl-ext repo and is now defunct (seems to not be indexed on CPAN
    at all).  So move them there so they can all be defunct together.

Are you sure you are using `Bio::Tools::dpAlign` ? I checked its source again, and indeed it uses `Bio::Ext::Align` which is not on CPAN.

The repository with all this stuff is at https://github.com/bioperl/bioperl-ext

**Comment by Stikus** [comment]
As you can see in VEP [README](https://github.com/Ensembl/ensembl-vep#bioperl-ext):
>haplo can make use of a fast compiled alignment algorithm from the bioperl-ext package; this can speed up analysis, particularly in longer transcripts where insertions and/or deletions are introduced. The bioperl-ext package is no longer maintained and requires some tweaking to install.

So yes - package is needed. What you suggest? Use old bioperl build or try to manually install `Bio::Tools::dpAlign`?
According to its code from [here](https://github.com/bioperl/bioperl-ext/blob/master/Bio/Tools/dpAlign.pm):
```perl
  use Bio::Tools::dpAlign;
  use Bio::SeqIO;
  use Bio::SimpleAlign;
  use Bio::AlignIO;
  use Bio::Matrix::IO;
```
Looks like I need all this packages too?

**Comment by carandraug** [comment]
> So yes - package is needed. What you suggest? Use old bioperl build or try to manually install Bio::Tools::dpAlign?

Suppose `Bio::Tools::dpAlign` was still in core bioperl. To make use of it you'd still need to install bioperl-ext which has been unmaintained for at least 6 years. So I suggest you do whatever VEP suggests you to do to install bioperl-ext. Since bioperl-ext is not on CPAN, I would expect VEP to suggest you to install bioperl-ext from development sources ( https://github.com/bioperl/bioperl-ext ). If you do that, then you should also also get `Bio::Tools::dpAlign`.

> According to its code from here:
>
> ```
>  use Bio::Tools::dpAlign;
>  use Bio::SeqIO;
>  use Bio::SimpleAlign;
>  use Bio::AlignIO;
>  use Bio::Matrix::IO;
> ```
>
> Looks like I need all this packages too?

Besides `Bio::Tools::dpAlign`, all others seem to still be in bioperl core.

**Comment by carandraug** [comment]
But to answer the question on this issue, which is "how to find where a module has been moved", I did `git log --stat` on the repository. The commit message that removed the module makes reference to the repository where the modules were moved to.

**Comment by Stikus** [comment]
Big thanks for answers, I'll try to get `Bio::Tools::dpAlign` from `bioperl-ext` installation.
And thanks for `git log --stat` idea.
Closing.
