### ISSUE TITLE
Testing Bio::DB::NCBIHelper-1.7.6 failed

### ISSUE THREAD

**Issue by tonyaseverson** [bioperl/bioperl-live#356]
I tried to install Bio::DB::Taxonomy::entrez, but cpanm reported a failed test. Force installing revealed that the problem may be with Bio::DB::NCBIHelper-1.7.6. I haven't seen any other reports of this issue, and the software I'm using (HMMER2GO) that requires Bio::DB::Taxonomy::entrez seems to be unaffected, but below are the specific lines of the Test Summary Report and I've attached the logfile here:
[1614304516.321615_build.log](https://github.com/bioperl/bioperl-live/files/6047734/1614304516.321615_build.log)

> Failed test at t/Taxonomy.t line 102.
>         got: 'Actinomycetia'
>    expected: 'Actinobacteria'
>Looks like you failed 1 test of 69.
>t/Taxonomy.t ...........
>Dubious, test returned 1 (wstat 256, 0x100)
>Failed 1/69 subtests
>
>Test Summary Report
>-------------------
>t/Taxonomy.t         (Wstat: 256 Tests: 69 Failed: 1)
>Failed test:  44
>Non-zero exit status: 1
>Files=9, Tests=175, 157 wallclock secs ( 0.05 usr  0.01 sys +  4.43 cusr  0.50 csys =  4.99 CPU)
>Result: FAIL
>Failed 1/9 test programs. 1/175 subtests failed.
>make: *** [Makefile:944: test_dynamic] Error 1
>-> FAIL Testing Bio-DB-NCBIHelper-1.7.6 failed but installing it anyway.

**Comment by cjfields** [comment]
This isn't out of the ordinary for remote tests, since any changes are largely out of our control. Just checking, b ut @tonyaseverson are you setting anything which runs entrez remote tests?  These are typically off by default and test only upon release (where we normally catch these issues).

**Comment by tonyaseverson** [comment]
Thanks, @cjfields. Certainly not on purpose! As far as I know the tests applied during installation were defaults, but it is possible that I did something fishy. I've been working mainly with python for the last 8 years, and was rusty on installing Perl packages. Unfortunately, the command-line I used appears to have dropped off my history.

**Comment by cjfields** [comment]
@tonyaseverson a recent pull request for Bio::DB::NCBIHelper fixed this, so I am closing this ticket.  Thanks for reporting!
