### ISSUE TITLE
Why Bio::SeqFeature::Generic can only get Seqfeature's source item?

### ISSUE THREAD

**Issue by CC3729** [bioperl/bioperl-live#372]
Dear everyone:
I wanted to obtain some coding region sequences from the mitochondrial genome by using the Bioperl script. I got a piece of core code from the official website, https://bioperl.org/howtos/Features_and_Annotations_HOWTO.html#item0, which should have achieved the effect of getting all tags and tag values from Seqfeature. But in fact, it seems like only can only get the source primary tag item, the other tags, such as "CDS", "gene", and "product", etc were missing. I don't know why. Am I running into a bug with Bioperl, or am I just doing it wrong?

The code and the accession number are as follows: 

for my $feat_object ($seq_object->get_SeqFeatures) { #https://bioperl.org/howtos/Features_and_Annotations_HOWTO.html
			print $display_name,"primary tag: ","\t", $feat_object->primary_tag, "\n";

			for my $tag ($feat_object->get_all_tags) {
				print "  tag: ","\t", $tag, "\n";
				for my $value ($feat_object->get_tag_values($tag)) {
					print "    value: ","\t", $value, "\n";
				}
			}
		}

Accession number:	
AY687385
AY962573
MT683848
LT992338

**Comment by CC3729** [comment]
> I didn't really see your full code in the formatted issue: this works for me (including downloading the data in genbank from NCBI):
> 
> ```perl
> #!/usr/bin/env perl
> use strict;
> use warnings;
> use Bio::SeqIO;
> my $urltemplate =
> 'http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nuccore&id=%s&rettype=gb&retmode=text';
> 
> # download data - assume you have curl installed
> 
> my @acc = qw(AY687385 AY962573 MT683848 LT992338);
> for my $acc (@acc) {
>     if ( !-f "$acc.gbk" ) {
>         my $url = sprintf( $urltemplate, $acc );
> 
>         # the -L deals with NCBI redirect
>         `curl -L -o $acc.gbk -O '$url'`;
>     }
>     my $in = Bio::SeqIO->new( -format => 'genbank', -file => "$acc.gbk" );
>     while ( my $seq = $in->next_seq ) {
>         printf( "seqid is %s:\n", $seq->display_id );
>         for my $feat_object ( $seq->get_SeqFeatures ) {
>             print join( "\t", 'primary tag:', $feat_object->primary_tag ), "\n";
>             for my $tag ( $feat_object->get_all_tags ) {
>                 print join("\t","  subtag: ", $tag), "\n";
>                 for my $value ( $feat_object->get_tag_values($tag) ) {
>                     print join("\t","    value: ",$value), "\n";
>                 }
>             }
>         }
>     }
> }
> ```

Thank you! I found my code mistakes. A variable is incorrectly defined. My full code was showed below:
use Bio::DB::GenBank;
use Bio::DB::Query::GenBank;
use Bio::SeqIO;
use Bio::SeqFeature::Generic; 

use utf8;
$file_name="test"; 
$tg_gene = "NADH dehydrogenase subunit 4";
open(QUERY_ID,"<","QUERY_ID_$file_name.txt") or die;
open (OUT, ">", "QuerySeqs_$file_name.fasta") || die;
open (OUT2, ">", "QueryInform_$file_name.txt") || die;

while ($query_id = <QUERY_ID>){
	
	$query = $query_id;   
	$query_obj = Bio::DB::Query::GenBank->new(-db => 'nucleotide', 
											  -query => $query );
	
	$gb_obj = Bio::DB::GenBank->new;
	
	$stream_obj = $gb_obj->get_Stream_by_query($query_obj);

	while ($seq_obj = $stream_obj->next_seq) {
		$display_name = $seq_obj -> display_name;
		$desc = $seq_obj -> desc;
		$seq = $seq_obj -> seq;
		$auth = $seq_obj -> authority;
		$speci = $seq_obj -> species -> node_name; 
		
		
		for my $feat_object ($seq_obj -> get_SeqFeatures) { 
			print $display_name,"primary tag: ","\t", $feat_object -> primary_tag, "\n";

			for my $tag ($feat_object -> get_all_tags) {
				print "  tag: ","\t", $tag, "\n";
				for my $value ($feat_object -> get_tag_values($tag)) {
					print "    value: ","\t", $value, "\n";
				}
			}
		}
				
		
		for my $feature($seq_obj -> get_SeqFeatures){
			if($feature -> has_tag("country")){
				print OUT ">", $display_name, "_", $spec, "_", join(",", $feature -> get_tag_values("country")),"\n";
				print OUT $seq, "\n\n";
				last;
			}else{
				print OUT ">", $display_name,  "_", $spec, "\n";
				print OUT $seq, "\n\n";
				last;
			}
		}
	}
}

close QUERY_ID;
close OUT;
close OUT;

**Comment by cjfields** [comment]
Okay, I'm assuming this is solved so closing it out
