### ISSUE TITLE
cant run VAMPr because of Bio::DB::Fasta

### ISSUE THREAD

**Issue by Hedi65** [bioperl/bioperl-live#384]
dear developer 

I can't run any of the VAMPr modules mainly because of this error 

Can't locate Bio/DB/Fasta.pm in @INC (you may need to install the Bio::DB::Fasta module) (@INC contains: /home/me/miniconda3/lib/site_perl/5.26.2/x86_64-linux-thread-multi /home/me/miniconda3/lib/site_perl/5.26.2 /home/me/miniconda3/lib/5.26.2/x86_64-linux-thread-multi /home/me/miniconda3/lib/5.26.2 .) at /home/me/VAMPr/VAMP.pl line 9.

BEGIN failed--compilation aborted at /home/me/VAMPr/VAMP.pl line 9.

by trying to update, I'm getting 
me@Minion:~$ sudo cpanm Bio::DB::Fasta
Bio::DB::Fasta is up to date. (1.7.8)

any help will appreciated.

**Comment by carandraug** [comment]
This looks weird but the fact that you closed it yourself one hour after, suggests that you figured it out yourself and it's not an issue for us to fix.
