### ISSUE TITLE
Alternative CI?

### ISSUE THREAD

**Issue by cjfields** [bioperl/bioperl-live#392]
Though I'd classify BioPerl as still useful, it's been essentially in 'maintenance' mode since ~2015 or so, with only minor updates and moving non-essential code into their own separate repositories.  Saying that, we should still re-implement some form of CI per-commit on the main development branch.  Travis-CI is broken but is no longer an option (see #325), so we will need to look into Perl-compatible alternatives if we want to continue forward with this.

**Comment by carandraug** [comment]
I see that Github actions is running the test suite on push so that's good. What else is needed? I don't know what travis was doing besides running the test suite.

**Comment by cjfields** [comment]
@carandraug You are absolutely correct, this is already taken care of (this is what happens when I don't check first!).  

The only thing I can think of is to remove any old Travis-CO hooks and the YAML file, and possibly update the Github CI for newer Perl stable releases.  Anything else? We can rename this issue to track those tasks.
