### ISSUE TITLE
Mismatched output in bp_taxid4species

### ISSUE THREAD

**Issue by zbwrnz** [bioperl/bioperl-live#86]
The bp_taxid4species script produces incorrect output.

```bash
$ bp_taxid4species "Arabidopsis thaliana" "Homo sapiens"
"arabidopsis thaliana[All Names]", 9606
"homo sapiens[All Names]", 3702
```
However the taxon id of A. thaliana should be 3702 and humans should be 9606.

The bug stems from a false assumption about Entrez output. As shown below

```bash
$ base='http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi'
$ term='Arabidopsis+thaliana+OR+Glycine+max'
$ wget -qO /dev/stdout "${base}?db=taxonomy&term=${term}" | xmlstarlet fo
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE eSearchResult PUBLIC "-//NLM//DTD esearch 20060628//EN" "http://eutils.ncbi.nlm.nih.gov/eutils/dtd/20060628/esearch.dtd">
<eSearchResult>
  <Count>2</Count>
  <RetMax>2</RetMax>
  <RetStart>0</RetStart>
  <IdList>
    <Id>3847</Id>
    <Id>3702</Id>
  </IdList>
  <TranslationSet/>
  <TranslationStack>
    <TermSet>
      <Term>arabidopsis thaliana[All Names]</Term>
      <Field>All Names</Field>
      <Count>1</Count>
      <Explode>N</Explode>
    </TermSet>
    <TermSet>
      <Term>glycine max[All Names]</Term>
      <Field>All Names</Field>
      <Count>1</Count>
      <Explode>N</Explode>
    </TermSet>
    <OP>OR</OP>
  </TranslationStack>
  <QueryTranslation>arabidopsis thaliana[All Names] OR glycine max[All Names]</QueryTranslation>
</eSearchResult>
```
Here I am using the same entrez query used in the bp_taxid4species. The \<Id\> terms in \<IdList\> and the \<TermSet\> terms in the \<TranslationStack\> are not in the same order. There is simply no way to map scientific names to taxon ids using this XML output.

One option would be to query entrez once for each species name. However this is slow.

A better option would be to extract the ids in IdList and then perform a second entrez query using the efetch or esummary utilities against the taxonomy database.

**Comment by pcantalupo** [comment]
Fixed in commit https://github.com/bioperl/bioperl-live/commit/054a689773ea92490162a48862098a80ae710145
