### ISSUE TITLE
Issues with bioperl versioning

### ISSUE THREAD

**Issue by cjfields** [bioperl/bioperl-live#87]
Blocker on new 1.6/1.7 releases,  see:

https://github.com/andk/pause/issues/75

**Comment by cjfields** [comment]
We're testing version issues with release candidates, which require PAUSE uploads to check.  Hopefully this is fixed.

**Comment by hlapp** [comment]
@cjfields I think this is fixed now, isn't it?

**Comment by cjfields** [comment]
@hlapp I believe so, only way to know is to make a final release (I'm working on the Changes docs).  I'll close, we can reopen if it's not fixed yet. 

I'll ping you on another issue re: adding something to the INSTALL.md documentation for Docker.

**Comment by cjfields** [comment]
Appears to still be an issue, this may require adding the version to the 'provides' section in the META.json/yml file, though that isn't the recommended route

**Comment by karenetheridge** [comment]
The simplest thing to do would be to have this in every .pm file:

    our $VERSION = '1.007000';

Right now most modules don't seem have a $VERSION at all.

**Comment by cjfields** [comment]
@karenetheridge : The issue is having to make those modifications to over 800 modules for every release, whereas the current method only requires having the version defined in one location.  The [only other workaround proposed](https://rt.cpan.org/Public/Bug/Display.html?id=92064#txn-1353433) would be adding the version to the `META.yml/json` in a `provides` section, though it seems [from the CPAN META spec](https://metacpan.org/pod/CPAN::Meta::Spec#provides) this isn't possible.

The odd thing is, you'll note that the [RT ticket](https://rt.cpan.org/Public/Bug/Display.html?id=92064#txn-1353433) specifically refers to v1.6.924 having issues, but it now is indexed with the correct version for all the modules.  I'm not sure how or when that occurred, but re-indexing didn't seem to address the problem with the v1.7.0 release.

**Comment by karenetheridge** [comment]
> The issue is having to make those modifications to over 800 modules for every release

That's why we generally have tools make that modification for us :)

> though it seems from the CPAN META spec this isn't possible

Could you please clarify what you're reading in the spec that is giving you that conclusion?

re the 1.007000 release not indexing, the email you got from PAUSE should explain the issue.

**Comment by karenetheridge** [comment]
Switching to Dist::Zilla is an option, true, but you can also just  `perl -p -i -e's/1.006924/1.007000/'; git commit lib -m'bumping version to 1.007000'`.

If the modules truly have no $VERSION, then meta-provides shouldn't say it did, but aren't you giving all the modules a version via a ::Version module?

**Comment by cjfields** [comment]
> Switching to Dist::Zilla is an option, true, but you can also just perl -p -i -e's/1.006924/1.007000/'; git commit lib -m'bumping version to 1.007000'.

I like the idea of using Dist::Zilla and not having to modify every file for a simply version bump (though I suppose it's really doing that during the build step anyway).

> If the modules truly have no $VERSION, then meta-provides shouldn't say it did, but aren't you giving all the modules a version via a ::Version module?

I read that line explicitly (e.g. each file has `$VERSION` defined), so I suppose that wasn't quite clear to me initially.  If revising `META.yml` works we'll try going with that option for now.

**Comment by cjfields** [comment]
@hlapp @karenetheridge seems to be fixed now with the 1.7.1 release.

**Comment by hlapp** [comment]
@cjfields so installing `Bio::Perl` should work now?

**Comment by cjfields** [comment]
@hlapp it should, if not we should reopen this bug

**Comment by cjfields** [comment]
@hlapp just tested and it seems to be working fine:

```
[cjfields@Chriss-MacBook-Air bioperl-live (master)]$ cpanm Bio::Perl
--> Working on Bio::Perl
Fetching http://www.cpan.org/authors/id/C/CJ/CJFIELDS/BioPerl-1.007001.tar.gz ... OK
...
```

**Comment by hlapp** [comment]
@cjfields yay it works: https://hub.docker.com/r/bioperl/bioperl/builds/bw2brzvtyqacqsuy6kams5h/
