### ISSUE TITLE
Speeding up DB::Fasta::subseq

### ISSUE THREAD

**Issue by rocky** [bioperl/bioperl-live#95]
This follows Pull request #96.  

The background is basically that in running Variant Effect Prediction, a significant portion of time is spent in the stripping carriage returns and line feeds in the subseq method via: 

    $data =~ s/\n//g;
    $data =~ s/\r//g

Compiling the match portion in a regular expression outside of the function helps, but better is doing it in C. 

[This commit](https://github.com/rocky/bioperl-live/commit/65e599b126d1598b594ecaca53777382686d0084) I hope will be acceptable, and if not should serve as a concrete discussion for further work. 

In that commit, in the [Inline-C-Fasts](https://github.com/rocky/bioperl-live/tree/Inline-C-Fasta) branch of my fork, if module Inline::C is around, that will compile use a C function that overwrites another function of the same name which is a pure Perl function.

See also these [benchmarks](https://gist.github.com/rocky/61f929d58a286189a758).

**Comment by fjossandon** [comment]
I was not trying to go OO, it was just a syntax confusion on my part. =)
Thanks for the explanation, now I have fixed the syntax and it works fine. I will push the change in a few minutes, once I run the test suite in case I overlooked something.

**Comment by fjossandon** [comment]
Ok, final edit on https://github.com/bioperl/bioperl-live/commit/01ec10dda23b6c5ed7592808cff4ae0d34278611. Issue closed

**Comment by rocky** [comment]
Ok, good to hear we're on the same page here. Looked over the final commits and it all looks good and better than before. Thanks!
