### ISSUE TITLE
bioperl-guts-l notifications

### ISSUE THREAD

**Issue by cjfields** [bioperl/bioperl-live#99]
Would like to get bioperl-guts-l notifications for github projects.  Will look into this.

**Comment by cjfields** [comment]
Note this mainly pertains to issues and pull request notifications.  Commits are working fine, but this is via the standard GitHub email hook (which doesn't seem to be configured for Issues).

**Comment by cjfields** [comment]
Does this work?  (e.g. this is a test)

**Comment by majensen** [comment]
Yep

On Mon, May 18, 2015 at 11:01 AM, Chris Fields < notifications@github.com [notifications@github.com] > wrote:
Does this work? (e.g. this is a test)

—
Reply to this email directly or view it on GitHub
[https://github.com/bioperl/bioperl-live/issues/99#issuecomment-103087812] .[https://github.com/notifications/beacon/AAFAmQ-09rxqA9hiCV6F0gKu4_MobZhOks5oKfYtgaJpZM4DQY_T.gif]

**Comment by cjfields** [comment]
@majensen ;)

well, I would really like this to go to bioperl-guts-l, but at least someone's getting it

**Comment by cjfields** [comment]
Appears to be working.  Initially set this up as a org-specific email notification under my account but that messes up settings for other orgs.  So, added @bioperl-guts (new 'user') to github and set it up that way.
